// laurel_st tree-sitter grammar.
// AUTO-GENERATED from the Strata DDM grammar.
// Do not edit by hand; run: lake env lean --run editors/GenSyntax.lean treesitter
// LR conflicts are loaded from conflicts.json; (re)generate it with:
//   node resolve-conflicts.cjs

const fs = require('fs');
const path = require('path');
let CONFLICTS = [];
try { CONFLICTS = JSON.parse(fs.readFileSync(path.join(__dirname, 'conflicts.json'), 'utf8')); }
catch (e) { /* no conflicts.json yet: run resolve-conflicts.cjs */ }

function commaSep(rule) { return optional(seq(rule, repeat(seq(',', rule)))); }
function semiSep(rule) { return optional(seq(rule, repeat(seq(';', rule)))); }

module.exports = grammar({
  name: 'laurel_st',

  extras: $ => [/\s/, $.comment],
  word: $ => $.identifier,
  conflicts: $ => CONFLICTS.map(group => group.map(name => $[name])),

  rules: {
    source_file: $ => seq(optional($.program_header), repeat($._command)),
    program_header: $ => seq('program', $.identifier, ';'),
    _command: $ => choice($._composite, $._procedure, $._datatype, $._constrained_type),
    _laurel_type: $ => choice($.int_type, $.bool_type, $.real_type, $.float64_type, $.string_type, $.bv_type, $.core_type, $.map_type, $.identifier),
    _stmt_expr: $ => choice($.boolean, $.number, $.decimal, $.string, $.hole, $.nondet_hole, $.var_decl, $.call, $.new, $.field_access, $.identifier, $.parenthesis, $.assign, $.multi_assign, $.add, $.sub, $.mul, $.div, $.mod, $.div_t, $.mod_t, $.eq, $.neq, $.gt, $.lt, $.le, $.ge, $.and, $.or, $.and_then, $.or_else, $.implies, $.str_concat, $.not, $.neg, $.forall_expr, $.exists_expr, $.if_then_else, $.assert, $.assume, $.return, $.block, $.labelled_block, $.exit, $.while, $.for_loop, $.is_type, $.as_type),
    _type_annotation: $ => $.type_annotation,
    _initializer: $ => $.initializer,
    _assign_target: $ => choice($.assign_target_decl, $.identifier, $.assign_target_field),
    _trigger: $ => $.trigger,
    _error_summary: $ => $.error_summary,
    _else_branch: $ => $.else_branch,
    _invariant_clause: $ => $.invariant_clause,
    _parameter: $ => $.parameter,
    _field: $ => choice($.mutable_field, $.immutable_field),
    _extends: $ => $.extends,
    _composite: $ => $.composite,
    _datatype_constructor_arg: $ => $.datatype_constructor_arg,
    _datatype_constructor: $ => choice($.datatype_constructor, $.identifier),
    _datatype: $ => $.datatype,
    _return_type: $ => $.return_type,
    _invoke_on_clause: $ => $.invoke_on_clause,
    _requires_clause: $ => $.requires_clause,
    _ensures_clause: $ => $.ensures_clause,
    _modifies_clause: $ => choice($.modifies_clause, $.modifies_wildcard),
    _return_parameters: $ => $.return_parameters,
    _opaque_spec: $ => $.opaque_spec,
    _body: $ => choice($.body, $.external_body),
    _procedure: $ => choice($.procedure, $.function),
    _constrained_type: $ => $.constrained_type,
    int_type: $ => 'int',
    bool_type: $ => 'bool',
    real_type: $ => 'real',
    float64_type: $ => 'float64',
    string_type: $ => 'string',
    bv_type: $ => prec.right(1024, seq('bv', $.number)),
    core_type: $ => prec.right(1024, seq('Core', $.identifier)),
    map_type: $ => seq('Map', $._laurel_type, $._laurel_type),
    hole: $ => '<?>',
    nondet_hole: $ => '<??>',
    type_annotation: $ => prec.right(1024, seq(':', $._laurel_type)),
    initializer: $ => prec.right(1024, seq(':=', $._stmt_expr)),
    var_decl: $ => seq('var', $.identifier, optional($._type_annotation), optional($._initializer)),
    call: $ => seq($._stmt_expr, '(', commaSep($._stmt_expr), ')'),
    new: $ => prec.right(1024, seq('new', $.identifier)),
    field_access: $ => prec.left(90, seq($._stmt_expr, '#', $.identifier)),
    parenthesis: $ => seq('(', $._stmt_expr, ')'),
    assign: $ => prec.left(10, seq($._stmt_expr, ':=', $._stmt_expr)),
    assign_target_decl: $ => seq('var', $.identifier, ':', $._laurel_type),
    assign_target_field: $ => prec.left(1024, seq($.identifier, '#', $.identifier)),
    multi_assign: $ => seq('assign', commaSep($._assign_target), ':=', $._stmt_expr),
    add: $ => prec.left(60, seq($._stmt_expr, '+', $._stmt_expr)),
    sub: $ => prec.left(60, seq($._stmt_expr, '-', $._stmt_expr)),
    mul: $ => prec.left(70, seq($._stmt_expr, '*', $._stmt_expr)),
    div: $ => prec.left(70, seq($._stmt_expr, '/', $._stmt_expr)),
    mod: $ => prec.left(70, seq($._stmt_expr, '%', $._stmt_expr)),
    div_t: $ => prec.left(70, seq($._stmt_expr, '/t', $._stmt_expr)),
    mod_t: $ => prec.left(70, seq($._stmt_expr, '%t', $._stmt_expr)),
    eq: $ => prec.left(40, seq($._stmt_expr, '==', $._stmt_expr)),
    neq: $ => prec.left(40, seq($._stmt_expr, '!=', $._stmt_expr)),
    gt: $ => prec.left(40, seq($._stmt_expr, '>', $._stmt_expr)),
    lt: $ => prec.left(40, seq($._stmt_expr, '<', $._stmt_expr)),
    le: $ => prec.left(40, seq($._stmt_expr, '<=', $._stmt_expr)),
    ge: $ => prec.left(40, seq($._stmt_expr, '>=', $._stmt_expr)),
    and: $ => prec.left(30, seq($._stmt_expr, '&', $._stmt_expr)),
    or: $ => prec.left(20, seq($._stmt_expr, '|', $._stmt_expr)),
    and_then: $ => prec.left(30, seq($._stmt_expr, '&&', $._stmt_expr)),
    or_else: $ => prec.left(20, seq($._stmt_expr, '||', $._stmt_expr)),
    implies: $ => prec.right(15, seq($._stmt_expr, '==>', $._stmt_expr)),
    str_concat: $ => prec.left(60, seq($._stmt_expr, '++', $._stmt_expr)),
    not: $ => prec.right(80, seq('!', $._stmt_expr)),
    neg: $ => prec.right(80, seq('-', $._stmt_expr)),
    trigger: $ => seq('{', $._stmt_expr, '}'),
    forall_expr: $ => seq('forall', '(', $.identifier, ':', $._laurel_type, ')', optional($._trigger), '=>', $._stmt_expr),
    exists_expr: $ => seq('exists', '(', $.identifier, ':', $._laurel_type, ')', optional($._trigger), '=>', $._stmt_expr),
    error_summary: $ => prec.right(1024, seq('summary', $.string)),
    else_branch: $ => prec.right(0, seq('else', $._stmt_expr)),
    if_then_else: $ => seq('if', $._stmt_expr, 'then', $._stmt_expr, optional($._else_branch)),
    assert: $ => seq('assert', $._stmt_expr, optional($._error_summary)),
    assume: $ => prec.right(0, seq('assume', $._stmt_expr)),
    return: $ => prec.right(0, seq('return', $._stmt_expr)),
    block: $ => seq('{', semiSep($._stmt_expr), '}'),
    labelled_block: $ => seq('{', semiSep($._stmt_expr), '}', $.identifier),
    exit: $ => prec.right(0, seq('exit', $.identifier)),
    invariant_clause: $ => prec.right(1024, seq('invariant', $._stmt_expr)),
    while: $ => seq('while', '(', $._stmt_expr, ')', repeat($._invariant_clause), $._stmt_expr),
    for_loop: $ => seq('for', '(', $._stmt_expr, ';', $._stmt_expr, ';', $._stmt_expr, ')', repeat($._invariant_clause), $._stmt_expr),
    parameter: $ => prec.left(1024, seq($.identifier, ':', $._laurel_type)),
    mutable_field: $ => seq('var', $.identifier, ':', $._laurel_type),
    immutable_field: $ => seq($.identifier, ':', $._laurel_type),
    is_type: $ => prec.left(40, seq($._stmt_expr, 'is', $.identifier)),
    as_type: $ => prec.left(40, seq($._stmt_expr, 'as', $.identifier)),
    extends: $ => prec.right(1024, seq('extends', commaSep($.identifier))),
    datatype_constructor_arg: $ => prec.left(1024, seq($.identifier, ':', $._laurel_type)),
    datatype_constructor: $ => seq($.identifier, '(', commaSep($._datatype_constructor_arg), ')'),
    datatype: $ => seq('datatype', $.identifier, '{', optional((commaSep($._datatype_constructor))), '}'),
    return_type: $ => prec.right(1024, seq(':', $._laurel_type)),
    invoke_on_clause: $ => prec.right(1024, seq('invokeOn', $._stmt_expr)),
    requires_clause: $ => seq('requires', $._stmt_expr, optional($._error_summary)),
    ensures_clause: $ => seq('ensures', $._stmt_expr, optional($._error_summary)),
    modifies_clause: $ => prec.right(1024, seq('modifies', commaSep($._stmt_expr))),
    modifies_wildcard: $ => seq('modifies', '*'),
    return_parameters: $ => seq('returns', '(', commaSep($._parameter), ')'),
    opaque_spec: $ => seq('opaque', repeat($._ensures_clause), repeat($._modifies_clause)),
    body: $ => prec.right(1024, $._stmt_expr),
    external_body: $ => 'external',
    procedure: $ => seq('procedure', $.identifier, '(', commaSep($._parameter), ')', optional($._return_type), optional($._return_parameters), repeat($._requires_clause), optional($._invoke_on_clause), optional($._opaque_spec), optional($._body), ';'),
    function: $ => seq('function', $.identifier, '(', commaSep($._parameter), ')', optional($._return_type), optional($._return_parameters), repeat($._requires_clause), optional($._invoke_on_clause), optional($._opaque_spec), optional($._body), ';'),
    composite: $ => seq('composite', $.identifier, optional($._extends), '{', repeat($._field), repeat($._procedure), '}'),
    constrained_type: $ => seq('constrained', $.identifier, '=', $.identifier, ':', $._laurel_type, 'where', $._stmt_expr, 'witness', $._stmt_expr),
    comment: $ => token(seq('//', /.*/)),
    identifier: $ => /[A-Za-z_$][A-Za-z0-9_$]*/,
    number: $ => /[0-9]+/,
    decimal: $ => /[0-9]+\.[0-9]+/,
    string: $ => /"([^"\\]|\\.)*"/,
    boolean: $ => choice('true', 'false'),
  }
});
