/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/
module
public import Strata.Pipeline.Messages

public import Strata.Languages.Core
public import Strata.Languages.Laurel.LaurelAST
public import Strata.Languages.Laurel.LaurelCompilationPipeline
import Strata.Languages.Laurel.Grammar.ConcreteToAbstractTreeTranslator
import Strata.Languages.Laurel.Grammar.AbstractToConcreteTreeTranslator
import Strata.Languages.Laurel.Grammar.LaurelGrammar
import StrataDDM.Elab
import Strata.Util.IonDeserializer

/-! ## Strata Laurel API

Reading, translating, and analyzing Laurel programs.
-/

public section

namespace Strata

/-- Deserializer for the struct-format Ion encoding of `Laurel.Program`,
generated by `getIonSerializer%`. -/
private partial def deserializeLaurelProgram : ByteArray → Except Std.Format Laurel.Program :=
  getIonDeserializer% Laurel.Program

/-! ### File I/O -/

/--
Read a Laurel source file in textual format and parse it into
a `Laurel.Program`. Handles dialect loading, parsing, and
AST translation in one step.
-/
def parseLaurelText (path : System.FilePath) (content : String)
    : IO Laurel.Program := do
  let input := StrataDDM.Parser.stringInputContext path content
  let dialects :=
    StrataDDM.Elab.LoadedDialects.ofDialects!
      #[StrataDDM.initDialect, Strata.Laurel.Laurel]
  let strataProgram ←
    StrataDDM.Elab.parseStrataProgramFromDialect
      dialects Strata.Laurel.Laurel.name input
  let uri := Strata.Uri.file path.toString
  match Strata.Laurel.TransM.run uri
      (Strata.Laurel.parseProgram strataProgram) with
  | .ok program => pure program
  | .error errors =>
    throw (IO.userError s!"Laurel translation errors: {errors}")

def readLaurelTextFile (path : System.FilePath)
    : IO Laurel.Program := do
  let content ← IO.FS.readFile path
  parseLaurelText path content

/--
Deserialize Laurel Ion bytes into a `Laurel.Program`.
Expects the struct-format encoding produced by `getIonSerializer%`.
-/
def readLaurelIonProgram (bytes : ByteArray)
    : IO Laurel.Program := do
  match deserializeLaurelProgram bytes with
  | .ok program => return program
  | .error e => throw (IO.userError s!"Failed to deserialize Laurel program: {e}")

/-! ### Transformation between generic and dialect-specific representation -/

/--
Translate a program in the dialect-specific AST for Laurel into the generic Strata
AST. Usually useful as a step before serialization.
-/
def laurelToStrataProgram (p : Laurel.Program) : StrataDDM.Program :=
  Laurel.programToStrata p

/--
Translate a program in the generic AST for Strata into the dialect-specific AST
for Laurel. This can fail with an error message if the input is not a
well-structured instance of the Laurel dialect.

`uri` names the file `p` was parsed from; it is recorded in the source location
of every translated AST node.
-/
def strataProgramToLaurel (uri : Uri) (p : StrataDDM.Program) : Except String Laurel.Program :=
  Laurel.TransM.run uri (Laurel.parseProgram p)

/-! ### Transformation between dialects -/

/--
Translate a program represented in the dialect-specific AST for the Laurel
dialect into the dialect-specific AST for the Core dialect. This can fail with
an error message if the input program contains constructs that are not yet
supported.
-/
def laurelToCore (p : Laurel.Program) : IO (Except String Core.Program) := do
  let (coreOpt, diags) ← Laurel.translate { } p
  match coreOpt with
  | some core => return .ok core
  | none => return .error s!"Laurel to Core translation failed: {diags.map (·.message)}"

/-! ### Analysis of Laurel programs -/

/--
Analyze a Laurel program by translating to Core and running
verification. Returns VC results (if translation succeeded)
and any translation diagnostics.
-/
def Laurel.verifyProgram
    (program : Laurel.Program)
    (options : Core.VerifyOptions := .default)
    : IO (Option Core.VCResults × List Message) :=
  Strata.Laurel.verifyToVcResults program { verifyOptions := options }

/--
Analyze a Laurel program and return structured diagnostic models
(combining translation errors and verification results).
-/
def Laurel.analyzeToMessages
    (program : Laurel.Program)
    (options : Core.VerifyOptions := .default)
    : IO (Array Message) :=
  Strata.Laurel.verifyToMessages program { verifyOptions := options }

end Strata

end -- public section
