/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/

namespace Core

/--
Controls irrelevant-axiom removal during verification. This mode is intended
only for _assert_-style proof obligations (deductive verification). Axiom
removal is **never** applied to _cover_ obligations, where it would be unsound:
removing an axiom weakens the path conditions, potentially making unreachable
paths appear satisfiable and producing spurious "covered" results.

## Soundness for assert obligations

Consider a goal `G: P ==> Q`, where `P` contains an axiom/assumption `A`. If
`A` is removed, we get `G': P' ==> Q`, where `P'` is a weaker version of `P`.
`G'` is therefore a stronger version of `G`. For soundness w.r.t. deductive
verification, we want: if `G'` is valid, then `G` was valid (but not necessarily
the converse).

**Case 1: `G'` is valid.**
Since `P' ==> P`, we have `P ==> Q`, i.e., `G` is valid too. Soundness is
preserved.

**Case 2: `G'` is invalid.**
There exists a model `M` for which `G'` is false, i.e., `M ⊨ P'` but `M ⊭ Q`.
This alone doesn't tell us about the validity of `G`:
- If `M ⊨ P` (i.e., `M` also satisfies the removed axiom `A`), then `M` is a
  counterexample for `G` too, so `G` is invalid too. Thus, a counterexample can
  be validated by checking if it satisfies `P`.
- If `M ⊭ P` (i.e., `M` violates the removed axiom `A`), then `M` is not a
  valid counterexample for `G`, and `G` might still be valid.

**Case 3: Validity of `G'` cannot be determined.**
This can be due to various reasons, like solver timeout, problem's complexity,
or incomplete solver theories. `G` could be valid, invalid, or undecidable.

**Soundness guarantee:** Axiom removal does not lead to proofs of invalid goals,
but it may cause valid goals to become unprovable, resulting in "unknown"
results. Moreover, if a counterexample is found for the weakened goal, it may
not be a valid counterexample for the original goal.

Note that soundness is preserved regardless of the quality of axiom relevance
analysis.
-/
inductive IrrelevantAxiomsMode where
  /--
  Only the functions in the consequent `Q` of a goal `P ==> Q` will be taken
  into account for relevant axiom analysis. This means that axioms relevant to
  some function in `P` (but not in `Q`) may be removed. This is sound, but may
  yield unknown results from the solver.
  -/
  | Aggressive
  /--
  Functions in both `P` and `Q` of a goal `P ==> Q` will be considered for
  relevant axiom analysis.
  -/
  | Precise
  /-- Do not prune any axioms. -/
  | Off
  deriving Repr, DecidableEq, Inhabited

inductive VerboseMode where
  | quiet
  | models
  | normal
  | debug
  deriving Inhabited, Repr, DecidableEq

def VerboseMode.toNat (v : VerboseMode) : Nat :=
  match v with
  | .quiet => 0
  | .models => 1
  | .normal => 2
  | .debug => 3

def VerboseMode.ofBool (b : Bool) : VerboseMode :=
  match b with
  | false => .quiet
  | true => .normal

instance : Coe VerboseMode Nat where
  coe := VerboseMode.toNat

instance : LT VerboseMode where
  lt a b := a.toNat < b.toNat

instance : DecidableRel (fun a b : VerboseMode => a < b) :=
  fun a b => decidable_of_iff (a.toNat < b.toNat) Iff.rfl

instance : LE VerboseMode where
  le a b := a.toNat ≤ b.toNat

instance : DecidableRel (fun a b : VerboseMode => a ≤ b) :=
  fun a b => decidable_of_iff (a.toNat ≤ b.toNat) Iff.rfl

/-- Default SMT solver to use -/
def defaultSolver : String := "cvc5"

structure VerifyOptions where
  verbose : VerboseMode
  parseOnly : Bool
  typeCheckOnly : Bool
  checkOnly : Bool
  stopOnFirstError : Bool
  removeIrrelevantAxioms : IrrelevantAxiomsMode
  /-- Use SMT-LIB Array theory instead of axiomatized maps -/
  useArrayTheory : Bool
  /-- Solver time limit in seconds -/
  solverTimeout : Nat
  /-- Output results in SARIF format -/
  outputSarif : Bool
  /-- SMT solver executable to use -/
  solver : String
  /-- Directory to store VCs -/
  vcDirectory : Option System.FilePath
  /--
  Enable reachability checks for all assert and cover statements.
  When enabled, the verifier emits an extra `(check-sat)` before each
  proof obligation to test whether the path-condition assumptions are
  satisfiable. If they are not (i.e., the code path is unreachable),
  the obligation is reported as `❗ unreachable` instead of the
  normal pass/fail outcome.

  This flag applies to **every** obligation that reaches the verifier,
  including obligations generated by transforms such as call elimination
  (precondition asserts) and procedure inlining. Individual statements
  can also opt in via the `@[reachCheck]` annotation without enabling
  this global flag.

  Off by default. CLI: `--reach-check`. -/
  reachCheck : Bool

def VerifyOptions.default : VerifyOptions := {
  verbose := .normal,
  parseOnly := false,
  typeCheckOnly := false,
  checkOnly := false,
  stopOnFirstError := false,
  removeIrrelevantAxioms := .Off,
  useArrayTheory := false,
  solverTimeout := 10,
  outputSarif := false,
  solver := defaultSolver
  vcDirectory := .none
  reachCheck := false
}

instance : Inhabited VerifyOptions where
  default := .default

def VerifyOptions.quiet : VerifyOptions :=
  { VerifyOptions.default with verbose := .quiet }

def VerifyOptions.models : VerifyOptions :=
  { VerifyOptions.default with verbose := .models }

def VerifyOptions.debug : VerifyOptions :=
  { VerifyOptions.default with verbose := .debug }

end Core
