/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/
module

public import Strata.Transform.NondetElimCorrect
public import Strata.Transform.LoopInitHoistCorrect
public import Strata.Transform.StructuredToUnstructuredCorrect
public import Strata.Transform.StructuredToUnstructuredPipeline
public import Strata.DL.Imperative.StmtSemanticsProps
public import Strata.Languages.Core.Expressions

import all Strata.Transform.NondetElim
import all Strata.Transform.LoopInitHoistCorrect

/-! # Structured-to-unstructured pipeline: soundness

The whole-pipeline correctness proof.  The key results are:

- `pipeline_overapproximates_upto_via_passes` — the abstract-form top-level
  correctness: the whole-pipeline `OverapproximatesUptoWhen` instance, composing
  the three per-pass instances.
- `pipelinePre_nil` — the syntactic precondition gate is inhabited.

The pipeline definitions themselves live in `StructuredToUnstructuredPipeline`. -/

public section

namespace Imperative

variable {P : PureExpr}

/-- A name generated by `nondetElim` is not an `s2uKind` label: the generator
prefixes differ, so the prefix relation is refuted by a head clash. -/
private theorem ndelim_name_not_s2uKind (sg : StringGenState) :
    ¬ StructuredToUnstructuredCorrect.s2uKind (StringGenState.gen ndelimItePrefix sg).1
  ∧ ¬ StructuredToUnstructuredCorrect.s2uKind (StringGenState.gen ndelimLoopPrefix sg).1 := by
  refine ⟨?_, ?_⟩ <;>
  · rw [StringGenState.gen_eq]
    rintro (⟨_, hpref, _⟩ | ⟨_, hpref, _⟩ | ⟨_, hpref, _⟩ | ⟨_, hpref, _⟩ |
            ⟨_, hpref, _⟩ | ⟨_, hpref, _⟩ | ⟨_, hpref, _⟩ | ⟨_, hpref, _⟩ |
            ⟨_, hpref, _⟩ | ⟨_, hpref, _⟩ | ⟨_, hpref, _⟩ | ⟨_, hpref, _⟩ |
            ⟨_, _, hpref, _⟩) <;>
      simp only [String.HasGenPrefix, ndelimItePrefix, ndelimLoopPrefix,
        iteLabelPrefix, nondetItePrefix, iteFlushPrefix, loopEntryPrefix, loopMeasurePrefix,
        measureDecreasePrefix, invariantPrefix, nondetLoopPrefix, endPrefix, listTailPrefix,
        blockFlushPrefix, beforeLoopPrefix, blockExitPrefix,
        String.toList_append] at hpref <;>
      · rw [List.isPrefixOf_iff_prefix] at hpref
        obtain ⟨t, ht⟩ := hpref
        simp only [String.toList, show (toString "block$") = "block$" from rfl] at ht
        -- character 0 clash for the eleven non-`$` prefixes; character 4 clash
        -- (`o`/`n` vs. ndelim `d`) for the two `$`-leading nondet prefixes.
        first
          | exact absurd (List.cons.inj ht).1 (by decide)
          | exact absurd
              (List.cons.inj (List.cons.inj (List.cons.inj
                (List.cons.inj (List.cons.inj ht).2).2).2).2).1 (by decide)

/-- Kind-level form: any `ndelimKind` string is not an `s2uKind` string. -/
private theorem ndelimKind_not_s2uKind {s : String} (h : ndelimKind s) :
    ¬ StructuredToUnstructuredCorrect.s2uKind s := by
  rcases h with ⟨sg, _, he⟩ | ⟨sg, _, he⟩
  · exact he ▸ (ndelim_name_not_s2uKind sg).1
  · exact he ▸ (ndelim_name_not_s2uKind sg).2

open Imperative.Specification
open Imperative.Specification.Transform
open Imperative.Logic

variable [HasFvar P] [HasFvars P] [HasBoolOps P]
  [HasIdent P] [HasInt P] [HasIntOps P] [DecidableEq P.Ident]
  [LawfulHasFvar P] [LawfulHasIdent P]

/-- Under `PipelinePre`, `nondetElim` overapproximates the source imperative-block
language by itself up to `EnvStoreAgree`, with source kind `pipelineKind` and target
kind `s2uKind`. -/
private theorem nondetElim_overapproximates_upto [HasSubstFvar P]
    (extendFactory : ExtendFactory P) :
    Specification.Transform.OverapproximatesUptoWhen
      (· = ·)
      (EnvStoreAgree (P := P))
      (Lang.imperativeBlock (EvalCmd P) extendFactory (isAtAssert P))
      (Lang.imperativeBlock (EvalCmd P) extendFactory (isAtAssert P))
      (fun ss => some (Block.nondetElim ss))
      (fun ss => PipelinePre ss)
      pipelineKind StructuredToUnstructuredCorrect.s2uKind := by
  -- Bridge to the same-file `nondetElim_overapproximates_upto_local`: the arms and
  -- `CanFail` transfer by definitional equality (both languages derive `star`/`stmtCfg`/
  -- terminal/exiting from the same `imperativeBlock`; both relations are `EnvStoreAgree`), and
  -- the initial-env `BlockInitEnvWF` is re-keyed from `pipelineKind` down to `ndelimKind`
  -- for the local lemma and up to `s2uKind` for the target conjunct.
  intro ss ss' ht hpre ρ₀ ρ₀' hEq hwf
  subst hEq
  simp only [Option.some.injEq] at ht
  subst ht
  have h_gens_ndelim : Env.varsUndefined (P := P) ndelimKind ρ₀ :=
    Env.varsUndefined_of_imp (fun _ hs => Or.inl hs) hwf.definedVarsNotReserved
  have h_gens_s2u : Env.varsUndefined (P := P) StructuredToUnstructuredCorrect.s2uKind ρ₀ :=
    Env.varsUndefined_of_imp (fun _ hs => Or.inr hs) hwf.definedVarsNotReserved
  obtain ⟨h_arms, h_canfail, _⟩ :=
    nondetElim_overapproximates_upto_local (P := P) extendFactory ss (Block.nondetElim ss) rfl
      ⟨hpre.h_nofd, hpre.h_unique, hpre.h_ndelim_writes⟩
      ρ₀ ρ₀ rfl
      ⟨hwf.toWellFormedSemanticEval, hwf.defsUndefined, h_gens_ndelim⟩
  refine ⟨h_arms, h_canfail,
    { hwf.toWellFormedSemanticEval with defsUndefined := ?_, definedVarsNotReserved := h_gens_s2u }⟩
  -- `nondetElim`-output initVars are undefined in ρ₀: source `initVars`
  -- (`hwf.defsUndefined`) or `ndelimKind`-generated (`h_gens_ndelim`).
  intro x hx
  rcases Block.nondetElimM_initVars_classified ss StringGenState.emp x hx with
    h_src | ⟨str, h_eq, h_nd⟩
  · exact hwf.defsUndefined x h_src
  · rw [h_eq]; exact Env.varsUndefined_apply h_gens_ndelim str h_nd

/-! ## Cross-pass `pre`-implication lemmas (composition)

The two lemmas below discharge each next pass's `pre` on the previous pass's
output — the `hpre` bridges `comp_trans_eq` needs to chain the per-pass instances.
The facts are the structural-preservation properties of the `nondetElim`/`hoist`
outputs, derived from the statement-only `pre`s. -/

omit [LawfulHasFvar P] in
/-- The `nondetElim` output satisfies the `hoist` pass's precondition whenever the
source satisfies `PipelinePre`. -/
private theorem hpre_src_ndelim [HasSubstFvar P] :
    ∀ ss ss', (fun ss => some (Block.nondetElim ss)) ss = some ss' →
      (fun ss => PipelinePre ss) ss →
      (fun ss =>
        Block.containsNondetLoop ss = false
        ∧ Block.noFuncDecl ss = true
        ∧ Block.loopHasNoInvariants ss = true
        ∧ Block.noMeasureLoops ss = true
        ∧ Block.uniqueInits ss
        ∧ Block.exitsCoveredByBlocks [] ss
        ∧ Block.noNondetGuards ss = true
        ∧ Block.userLabelsShapeNodup ss
        ∧ (∀ s : String, StructuredToUnstructuredCorrect.s2uKind s →
            HasIdent.ident (P := P) s ∉ Block.initVars ss)) ss' := by
  intro ss ss' ht hpre
  simp only [Option.some.injEq] at ht
  subst ht
  refine ⟨nondetElim_containsNondetLoop ss,
    nondetElim_noFuncDecl ss hpre.h_nofd,
    nondetElim_loopHasNoInvariants ss hpre.h_lhni,
    ?_, ?_, ?_, ?_, ?_, ?_⟩
  · -- `noMeasureLoops (nondetElim ss) = true`.
    exact nondetElim_noMeasureLoops ss hpre.h_nml
  · -- `uniqueInits (nondetElim ss)`.
    exact (Block.nondetElimM_initVars_nodup ss StringGenState.emp StringGenState.wf_emp
      hpre.h_unique (fun str hk => hpre.h_disj_initVars str (Or.inl hk))).2
  · -- exit coverage is preserved by `nondetElim`.
    exact Block.nondetElim_exitsCoveredByBlocks ss hpre.h_covered
  · -- `noNondetGuards (nondetElim ss) = true` (`nondetElim` removes every nondet guard).
    exact nondetElim_noNondetGuards ss
  · -- `userLabelsShapeNodup (nondetElim ss)`: `nondetElim` preserves `getBlockLabels`.
    unfold Block.userLabelsShapeNodup
    rw [Block.nondetElim_getBlockLabels]
    exact hpre.h_userlabels
  · -- `s2uKind`-freedom of `initVars (nondetElim ss)`.
    intro str hk hmem
    rcases Block.nondetElimM_initVars_classified ss StringGenState.emp _ hmem with
      h_src | ⟨str', h_eq, h_nd⟩
    · exact hpre.h_disj_initVars str (Or.inr hk) h_src
    · exact ndelimKind_not_s2uKind h_nd (LawfulHasIdent.ident_inj h_eq ▸ hk)

omit [LawfulHasFvar P] [HasFvar P] [HasBoolOps P] in
omit [HasInt P] [HasIntOps P] [DecidableEq P.Ident] [LawfulHasIdent P] in
/-- `pre_ndelim → pre_hoist ∘ hoistLoopPrefixInits`: the `stmtsToCFG` instance's
`pre` holds on the `hoist` output. -/
private theorem hpre_ndelim_hoist :
    ∀ ss ss', (fun ss => some (Block.hoistLoopPrefixInits ss)) ss = some ss' →
      (fun ss =>
        Block.containsNondetLoop ss = false
        ∧ Block.noFuncDecl ss = true
        ∧ Block.loopHasNoInvariants ss = true
        ∧ Block.noMeasureLoops ss = true
        ∧ Block.uniqueInits ss
        ∧ Block.exitsCoveredByBlocks [] ss
        ∧ Block.noNondetGuards ss = true
        ∧ Block.userLabelsShapeNodup ss
        ∧ (∀ s : String, StructuredToUnstructuredCorrect.s2uKind s →
            HasIdent.ident (P := P) s ∉ Block.initVars ss)) ss →
      (fun ss =>
        Block.noFuncDecl ss = true
        ∧ Block.noNondetGuards ss = true
        ∧ Block.uniqueInits ss
        ∧ Block.loopBodyNoInits ss = true
        ∧ Block.loopHasNoInvariants ss = true
        ∧ Block.noMeasureLoops ss = true
        ∧ Block.exitsCoveredByBlocks [] ss
        ∧ Block.userLabelsShapeNodup ss
        ∧ (∀ s : String, StructuredToUnstructuredCorrect.s2uKind s →
            HasIdent.ident (P := P) s ∉ Block.initVars ss)) ss' := by
  intro ss ss' ht hpre
  simp only [Option.some.injEq] at ht
  subst ht
  obtain ⟨_, h_no_fd, h_no_inv, h_no_measure, h_unique, h_covered,
    h_simple, h_userlabels, h_s2u_iv⟩ := hpre
  have h_nofd : Block.noFuncDecl ss = true := h_no_fd
  refine ⟨LoopInitHoistProducerProps.Block.hoistP_noFuncDecl ss h_nofd,
    LoopInitHoistProducerProps.Block.hoistP_noNondetGuards ss h_simple,
    (LoopInitHoistProducerProps.Block.hoistP_initVars_perm ss).nodup_iff.mpr h_unique,
    LoopInitHoistProducerProps.Block.hoistP_loopBodyNoInits ss,
    LoopInitHoistProducerProps.Block.hoistP_loopHasNoInvariants ss h_no_inv, ?_, ?_, ?_, ?_⟩
  · -- `noMeasureLoops (hoist' ss) = true` from `noMeasureLoops ss`.
    exact LoopInitHoistProducerProps.Block.hoistP_noMeasureLoops ss h_no_measure
  · -- exit coverage is preserved by the same-name hoist.
    exact Block.hoistP_exitsCoveredByBlocks [] ss h_covered
  · -- `userLabelsShapeNodup (hoist' ss)`: same-name hoist preserves `getBlockLabels`.
    unfold Block.userLabelsShapeNodup
    rw [LoopInitHoistProducerProps.Block.hoistP_getBlockLabels]
    exact h_userlabels
  · -- `s2uKind`-freedom of `initVars (hoist' ss)`: `initVars (hoist' ss)` ⊆ source
    -- `initVars` (`hoistP_initVars_sub`), so `s2uKind`-freedom transports.
    intro s hk hx
    exact h_s2u_iv s hk
      (LoopInitHoistProducerProps.Block.hoistP_initVars_sub ss (HasIdent.ident (P := P) s) hx)

/-! ## Composition of the three per-pass instances -/

/-- The three per-pass instances chained via `comp_trans_eq` (`EnvStoreAgree` is
transitive) into one source-`imperativeBlock` → `cfg` instance, with the monadic
composition of the three pass transforms and `pre = pre_src`.  The source
language's `initEnvWF` is keyed on the combined `pipelineKind`. -/
private theorem pipeline_overapproximates_upto_composed [HasSubstFvar P]
    (extendFactory : ExtendFactory P) :
    Specification.Transform.OverapproximatesUptoWhen
      (· = ·)
      (EnvStoreAgree (P := P))
      (Lang.imperativeBlock (EvalCmd P) extendFactory (isAtAssert P))
      (Lang.cfg extendFactory)
      (fun s => (fun s => some (Block.nondetElim s)) s >>=
        (fun s => (fun s => some (Block.hoistLoopPrefixInits s)) s >>=
          (fun s => some (stmtsToCFG s))))
      (fun ss => PipelinePre ss)
      pipelineKind () :=
  -- inner: `imperativeBlock(s2uKind) → cfg`, pre = pre_ndelim, via `hpre_ndelim_hoist`.
  have h_inner :=
    Specification.Transform.OverapproximatesUptoWhen.comp_trans_eq
      (R := EnvStoreAgree (P := P))
      (Lang.imperativeBlock (EvalCmd P) extendFactory (isAtAssert P))
      (Lang.imperativeBlock (EvalCmd P) extendFactory (isAtAssert P))
      (Lang.cfg extendFactory)
      (fun s => some (Block.hoistLoopPrefixInits s)) (fun s => some (stmtsToCFG s))
      StructuredToUnstructuredCorrect.s2uKind StructuredToUnstructuredCorrect.s2uKind ()
      (fun _ _ _ h₁ h₂ => EnvStoreAgree_trans h₁ h₂)
      hpre_ndelim_hoist
      (hoist_overapproximates_upto extendFactory)
      (StructuredToUnstructuredCorrect.stmtsToCFG_overapproximates_upto extendFactory)
  -- outer: source `imperativeBlock(pipelineKind) → cfg`, pre = pre_src, via `hpre_src_ndelim`.
  Specification.Transform.OverapproximatesUptoWhen.comp_trans_eq
    (R := EnvStoreAgree (P := P))
    (Lang.imperativeBlock (EvalCmd P) extendFactory (isAtAssert P))
    (Lang.imperativeBlock (EvalCmd P) extendFactory (isAtAssert P))
    (Lang.cfg extendFactory)
    (fun s => some (Block.nondetElim s))
    (fun s => (fun s => some (Block.hoistLoopPrefixInits s)) s >>= (fun s => some (stmtsToCFG s)))
    pipelineKind StructuredToUnstructuredCorrect.s2uKind ()
    (fun _ _ _ h₁ h₂ => EnvStoreAgree_trans h₁ h₂)
    hpre_src_ndelim
    (nondetElim_overapproximates_upto extendFactory)
    h_inner

omit [LawfulHasFvar P]
  [LawfulHasIdent P] [DecidableEq P.Ident]
 in
/-- The composed per-pass transform `nondetElim >=> hoist >=> stmtsToCFG`
collapses (each step is `some _`, so `Option.bind` reduces) to `some ∘ pipeline`,
since `pipeline = stmtsToCFG ∘ hoistLoopPrefixInits ∘ Block.nondetElim`. -/
private theorem pipeline_transform_eq (ss : List (Stmt P (Cmd P))) :
    ((fun s => some (Block.nondetElim s)) ss >>=
      (fun s => (fun s => some (Block.hoistLoopPrefixInits s)) s >>=
        (fun s => some (stmtsToCFG s)))) = some (s2uPipeline ss) := by
  simp only [s2uPipeline, Function.comp_apply, bind, Option.bind]

/-- **Pipeline overapproximation, via per-pass composition.**  The canonical
whole-pipeline refinement: `fun ss => some (s2uPipeline ss)` overapproximates the
source statement-list language by the unstructured CFG language up to
`EnvStoreAgree`. -/
theorem pipeline_overapproximates_upto_via_passes [HasSubstFvar P]
    (extendFactory : ExtendFactory P) :
    Specification.Transform.OverapproximatesUptoWhen
      (· = ·)
      (EnvStoreAgree (P := P))
      (Lang.imperativeBlock (EvalCmd P) extendFactory (isAtAssert P))
      (Lang.cfg extendFactory)
      (fun ss => some (s2uPipeline ss))
      (fun ss => PipelinePre ss)
      pipelineKind () := by
  have h := pipeline_overapproximates_upto_composed extendFactory
  -- Rewrite the composed transform to `some ∘ pipeline` (pointwise equal by
  -- `pipeline_transform_eq`).
  rwa [show (fun s => (fun s => some (Block.nondetElim s)) s >>=
      (fun s => (fun s => some (Block.hoistLoopPrefixInits s)) s >>=
        (fun s => some (stmtsToCFG s))))
      = (fun ss => some (s2uPipeline ss)) from funext pipeline_transform_eq] at h

/-- **The syntactic precondition is inhabited.**  The empty program satisfies
`PipelinePre`, ruling out global vacuity of the `fun ss => PipelinePre ss`
precondition. -/
theorem pipelinePre_nil {P : PureExpr} [HasFvar P] [HasFvars P] [HasBoolOps P]
    [HasIdent P] [HasInt P] [HasIntOps P]
    [HasSubstFvar P] [DecidableEq P.Ident] :
    PipelinePre ([] : List (Stmt P (Cmd P))) where
  h_nofd := by simp [Block.noFuncDecl]
  h_lhni := by simp [Block.loopHasNoInvariants]
  h_nml := by simp [Block.noMeasureLoops]
  h_unique := by simp [Block.uniqueInits, Block.initVars]
  h_userlabels := by simp [Block.userLabelsShapeNodup, Block.getBlockLabels]
  h_covered := by simp [Block.exitsCoveredByBlocks]
  h_ndelim_writes := by intro s _ hmem; exact absurd hmem (by simp)
  h_disj_initVars := by intro s _ hmem; exact absurd hmem (by simp [Block.initVars])

end Imperative

end -- public section
