/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/

import Strata.Transform.ProcBodyVerify
import StrataTest.Transform.SoundnessFramework

/-! # Procedure Body Verification Correctness Proof

Proves that `procToVerifyStmt` is sound: if all assertions in the
verification statement are valid, then the procedure obeys its contract.
-/

namespace ProcBodyVerifyCorrect

open Core Core.ProcBodyVerify Imperative Lambda Transform Soundness

/-! ## Operational Semantics Lemmas -/

/-- An assert statement is a skip: it preserves the store and evaluator -/
theorem eval_assert_is_skip
    (π : String → Option Procedure) (φ : CoreEval → PureFunc Expression → CoreEval)
    (δ : CoreEval) (σ σ' : CoreStore) (δ' : CoreEval)
    (label : CoreLabel) (expr : Expression.Expr) (md : MetaData Expression) :
    EvalStatement π φ δ σ (Statement.assert label expr md) σ' δ' →
    σ' = σ ∧ δ' = δ := by
  intro h
  unfold Statement.assert at h
  cases h with
  | cmd_sem h_cmd h_def =>
    cases h_cmd with
    | cmd_sem h_imp =>
      cases h_imp with
      | eval_assert => exact ⟨rfl, rfl⟩

/-- If an assume statement evaluates successfully, the condition holds -/
theorem eval_assume_implies_condition
    (π : String → Option Procedure) (φ : CoreEval → PureFunc Expression → CoreEval)
    (δ : CoreEval) (σ σ' : CoreStore) (δ' : CoreEval)
    (label : CoreLabel) (expr : Expression.Expr) (md : MetaData Expression) :
    EvalStatement π φ δ σ (Statement.assume label expr md) σ' δ' →
    δ σ expr = Option.some HasBool.tt ∧ σ' = σ ∧ δ' = δ := by
  intro h
  unfold Statement.assume at h
  cases h with
  | cmd_sem h_cmd h_def =>
    cases h_cmd with
    | cmd_sem h_imp =>
      cases h_imp with
      | eval_assume h_true h_wf => exact ⟨h_true, rfl, rfl⟩

/-- Evaluation of a block statement -/
theorem eval_block_iff
    (π : String → Option Procedure) (φ : CoreEval → PureFunc Expression → CoreEval)
    (δ : CoreEval) (σ σ' : CoreStore) (δ' : CoreEval)
    (label : String) (stmts : List Statement) (md : MetaData Expression) :
    EvalStatement π φ δ σ (Stmt.block label stmts md) σ' δ' ↔
    EvalStatements π φ δ σ stmts σ' δ' := by
  constructor
  · intro h; cases h with | block_sem h_block => exact h_block
  · intro h; exact Imperative.EvalStmt.block_sem h

/-! ## Soundness of ProcBodyVerify

`procToVerifyStmt` transforms a `Procedure` into a verification `Statement`:
```
block "verify_P" {
  init inputs; init outputs; init modifies;
  assume preconditions;
  block "body_P" { body... }
  assert postconditions;
}
```

Soundness: if all assertions in the verification statement are valid
(i.e., `stmt_correct` holds), then the procedure obeys its contract.

The proof proceeds in two parts:
1. Characterize the output of `procToVerifyStmt` structurally
2. Show that `stmt_correct` on that structure implies `procedure_obeys_contract`
-/

/-- The output of `procToVerifyStmt` is a block whose statements end with
    the postcondition asserts generated by `ensuresToAsserts`. -/
theorem procToVerifyStmt_has_asserts
    (proc : Procedure) (p : Program) (st : CoreTransformState)
    (stmt : Statement) (st' : CoreTransformState)
    (h : (procToVerifyStmt proc p).run st = (Except.ok stmt, st')) :
    ∃ (label : String) (prefix_ : List Statement) (md : MetaData Expression),
      stmt = Stmt.block label (prefix_ ++ ensuresToAsserts proc.spec.postconditions) md := by
  sorry

/-- Stepping through assert statements (which are skips) in a block preserves
    the store and evaluator. If all statements in `skips` are asserts, then
    `.block label (skips ++ rest) σ δ` can step to `.block label rest σ δ`. -/
theorem block_step_through_asserts
    (π : String → Option Procedure) (φ : CoreEval → PureFunc Expression → CoreEval)
    (label : String) (skips rest : List Statement) (σ : CoreStore) (δ : CoreEval)
    (h_all_asserts : ∀ s, s ∈ skips → ∃ l e m, s = Statement.assert l e m) :
    CoreStepStar π φ
      (.block label (skips ++ rest) σ δ)
      (.block label rest σ δ) := by
  induction skips with
  | nil => simp; exact ReflTrans.refl _
  | cons s skips' ih =>
    obtain ⟨l, e, m, rfl⟩ := h_all_asserts s (List.mem_cons.mpr (Or.inl rfl))
    apply ReflTrans.step _ (.block label (skips' ++ rest) σ δ)
    · -- One step: assert is a skip, block body advances
      exact StepStmt.step_block_body
        (StepStmt.step_stmt_cons
          (StepStmt.step_cmd (EvalCommand.cmd_sem EvalCmd.eval_assert)))
    · exact ih (fun s h => h_all_asserts s (List.mem_cons.mpr (Or.inr h)))

theorem block_correct_implies_asserts_hold
    (π : String → Option Procedure) (φ : CoreEval → PureFunc Expression → CoreEval)
    (label : String) (prefix_ asserts : List Statement) (md : MetaData Expression)
    (σ : CoreStore) (δ_eval : CoreEval)
    (h_correct : stmt_correct π φ (Stmt.block label (prefix_ ++ asserts) md))
    (h_prefix_exec : ∃ (δ₀ : CoreEval) (σ₀ : CoreStore),
      CoreStepStar π φ
        (.stmt (Stmt.block label (prefix_ ++ asserts) md) σ₀ δ₀)
        (.block label asserts σ δ_eval))
    (h_all_asserts : ∀ s, s ∈ asserts → ∃ l e m, s = Statement.assert l e m) :
    ∀ (lbl : CoreLabel) (expr : Expression.Expr) (amd : MetaData Expression),
      Statement.assert lbl expr amd ∈ asserts →
      δ_eval σ expr = some HasBool.tt := by
  intro lbl expr amd h_in
  obtain ⟨δ₀, σ₀, h_reach_block⟩ := h_prefix_exec
  -- Split asserts into (before_assert ++ [assert lbl expr amd] ++ after_assert)
  obtain ⟨before, after, h_split⟩ := List.append_of_mem h_in
  -- All statements in `before` are asserts (skips)
  have h_before_asserts : ∀ s, s ∈ before → ∃ l e m, s = Statement.assert l e m := by
    intro s h_s
    have : s ∈ asserts := h_split ▸ List.mem_append.mpr (Or.inl h_s)
    exact h_all_asserts s this
  -- Step through the `before` asserts to reach the target assert at the head
  have h_step_before := block_step_through_asserts π φ label before
    (Statement.assert lbl expr amd :: after) σ δ_eval h_before_asserts
  -- Rewrite asserts = before ++ [assert] ++ after everywhere
  subst h_split
  -- Now we have a path: stmt →* .block →* .block (assert :: after)
  have h_reach_assert : CoreStepStar π φ
      (.stmt (Stmt.block label (prefix_ ++ (before ++ Statement.assert lbl expr amd :: after)) md) σ₀ δ₀)
      (.block label (Statement.assert lbl expr amd :: after) σ δ_eval) :=
    ReflTrans_Transitive _ _ _ _ h_reach_block h_step_before
  have h_reachable : reachable π φ (Stmt.block label (prefix_ ++ (before ++ Statement.assert lbl expr amd :: after)) md)
      ⟨σ, δ_eval, some ⟨lbl, expr, amd⟩⟩ :=
    ⟨δ₀, σ₀, .block label (Statement.assert lbl expr amd :: after) σ δ_eval,
     h_reach_assert, rfl⟩
  exact h_correct ⟨lbl, expr, amd⟩ ⟨σ, δ_eval, some ⟨lbl, expr, amd⟩⟩ h_reachable rfl

/-- Soundness: if all assertions in the verification statement are valid,
    then the procedure obeys its contract. -/
theorem procBodyVerify_sound
    (π : String → Option Procedure) (φ : CoreEval → PureFunc Expression → CoreEval)
    (proc : Procedure) (p : Program) (st : CoreTransformState)
    (stmt : Statement) (st' : CoreTransformState)
    (h_transform : (procToVerifyStmt proc p).run st = (Except.ok stmt, st'))
    (h_correct : stmt_correct π φ stmt) :
    procedure_obeys_contract π φ proc := by
  -- Unfold procedure_obeys_contract
  intro δ σ₀ σ_final δ_final h_pre h_body label check h_post_in h_default
  -- 1. The verification statement is a block ending with postcondition asserts
  obtain ⟨blk_label, prefix_, blk_md, h_stmt_eq⟩ :=
    procToVerifyStmt_has_asserts proc p st stmt st' h_transform
  -- 2. The postcondition assert is in ensuresToAsserts
  have h_assert_in : Statement.assert label check.expr check.md ∈
      ensuresToAsserts proc.spec.postconditions := by
    unfold ensuresToAsserts
    simp only [List.mem_filterMap]
    exact ⟨(label, check), h_post_in, by simp [h_default]⟩
  -- 3. We need to show δ_final σ_final check.expr = some tt
  -- By h_correct (rewritten with h_stmt_eq) and the fact that the assert
  -- is reachable in the block with store σ_final and evaluator δ_final,
  -- the postcondition holds.
  -- The reachability requires constructing the execution path through
  -- the verification block: inits → assumes → body → asserts
  sorry

end ProcBodyVerifyCorrect
