/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/

import Strata.Languages.Core.Program
import Strata.Languages.Core.Verifier
import Strata.Languages.Core.Statement
import Strata.Languages.Core.Procedure
import Strata.Languages.Core.Options
import Strata.Languages.Laurel.Laurel
import Strata.Languages.Laurel.LiftImperativeExpressions
import Strata.Languages.Laurel.HeapParameterization
import Strata.Languages.Laurel.TypeHierarchy
import Strata.Languages.Laurel.LaurelTypes
import Strata.Languages.Laurel.ModifiesClauses
import Strata.Languages.Laurel.CorePrelude
import Strata.DL.Imperative.Stmt
import Strata.DL.Imperative.MetaData
import Strata.DL.Lambda.LExpr
import Strata.Languages.Laurel.LaurelFormat
import Strata.Util.Tactics

open Core (VCResult VCResults VerifyOptions)
open Core (intAddOp intSubOp intMulOp intDivOp intModOp intDivTOp intModTOp intNegOp intLtOp intLeOp intGtOp intGeOp boolAndOp boolOrOp boolNotOp boolImpliesOp strConcatOp)

namespace Strata.Laurel

open Std (Format ToFormat)
open Strata
open Lambda (LMonoTy LTy LExpr)

/-
Translate Laurel HighType to Core Type
-/
def translateType (ty : HighTypeMd) : LMonoTy :=
  match _h : ty.val with
  | .TInt => LMonoTy.int
  | .TBool => LMonoTy.bool
  | .TString => LMonoTy.string
  | .TVoid => LMonoTy.bool -- Using bool as placeholder for void
  | .THeap => .tcons "Heap" []
  | .TTypedField _ => .tcons "Field" []
  | .TSet elementType => Core.mapTy (translateType elementType) LMonoTy.bool
  | .TMap keyType valueType => Core.mapTy (translateType keyType) (translateType valueType)
  | .UserDefined _ => .tcons "Composite" []
  | .TCore s => .tcons s []
  | .Applied ctor [elemTy] =>
    match ctor.val with
    | .UserDefined "Array" => .tcons "Array" [translateType elemTy]
    | _ => panic s!"unsupported applied type {repr ty}"
  | _ => panic s!"unsupported type {ToFormat.format ty}"
termination_by ty.val
decreasing_by
  all_goals first
    | (cases elementType; term_by_mem)
    | (cases keyType; term_by_mem)
    | (cases valueType; term_by_mem)
    | (cases elemTy; term_by_mem)
    | (cases ctor; term_by_mem)


def isFieldName (fieldNames : List Identifier) (name : Identifier) : Bool :=
  fieldNames.contains name

/-- Set of names that are translated to Core functions (not procedures) -/
abbrev FunctionNames := List Identifier

def isCoreFunction (funcNames : FunctionNames) (name : Identifier) : Bool :=
  -- readField, updateField, and Box constructors/destructors are always functions
  name == "readField" || name == "updateField" || name == "increment" ||
  name == "MkHeap" || name == "Heap..data" || name == "Heap..nextReference" ||
  name == "MkComposite" || name == "Composite..ref" || name == "Composite..typeTag" ||
  name == "BoxInt" || name == "BoxBool" || name == "BoxFloat64" || name == "BoxComposite" ||
  name == "Box..intVal" || name == "Box..boolVal" || name == "Box..float64Val" || name == "Box..compositeVal" ||
  -- Map operations (select/update are built-in map functions, const creates a constant map)
  name == "select" || name == "update" || name == "const" ||
  -- Type hierarchy functions generated by typeHierarchyTransform
  name == "ancestorsPerType" || name.startsWith "ancestorsFor" || name.endsWith "_TypeTag" ||
  funcNames.contains name

/-- State threaded through expression and statement translation -/
abbrev ConstrainedTypeMap := Std.HashMap Identifier ConstrainedType

structure TranslatedConstraint where
  base : HighType
  valueName : Identifier
  coreConstraint : Core.Expression.Expr

abbrev TranslatedConstraintMap := Std.HashMap Identifier TranslatedConstraint
structure TranslateState where
  /-- Diagnostics accumulated during translation -/
  diagnostics : List DiagnosticModel := []
  /-- Constants known to the program (field constants, etc.) -/
  fieldNames : List String := []
  /-- Names of procedures that are translated as Core functions -/
  funcNames : FunctionNames := []
  /-- Constrained type definitions -/
  ctMap : ConstrainedTypeMap := {}
  /-- Pre-translated constraints -/
  tcMap : TranslatedConstraintMap := {}

/-- The translation monad: state over Id -/
abbrev TranslateM := StateT TranslateState Id

/-- Emit a diagnostic into the translation state -/
def emitDiagnostic (d : DiagnosticModel) : TranslateM Unit :=
  modify fun s => { s with diagnostics := s.diagnostics ++ [d] }

/-- Run a `TranslateM` action, returning the result and final state -/
def runTranslateM (s : TranslateState) (m : TranslateM α) : α × TranslateState :=
  m s

-- ============ Constrained type support ============


def buildConstrainedTypeMap (types : List TypeDefinition) : ConstrainedTypeMap :=
  types.foldl (init := {}) fun m td =>
    match td with
    | .Constrained ct => m.insert ct.name ct
    | _ => m

partial def resolveBaseType (ctMap : ConstrainedTypeMap) (ty : HighType) : HighType :=
  match ty with
  | .UserDefined name =>
    match ctMap.get? name with
    | some ct => resolveBaseType ctMap ct.base.val
    | none => ty
  | .Applied ctor args =>
    .Applied ctor (args.map fun arg => ⟨resolveBaseType ctMap arg.val, arg.md⟩)
  | _ => ty

def translateTypeWithCT (ctMap : ConstrainedTypeMap) (ty : HighTypeMd) : LMonoTy :=
  translateType ⟨resolveBaseType ctMap ty.val, ty.md⟩

def lookupType (env : TypeEnv) (name : Identifier) (ctMap : ConstrainedTypeMap := {}) : LMonoTy :=
  match env.find? (fun (n, _) => n == name) with
  | some (_, ty) => translateTypeWithCT ctMap ty
  | none => panic s!"could not find variable {name} in environment '{Std.format env}'"
def lookupTypeWithCT (ctMap : ConstrainedTypeMap) (env : TypeEnv) (name : Identifier) : Except String LMonoTy :=
  match env.find? (fun (n, _) => n == name) with
  | some (_, ty) => pure (translateTypeWithCT ctMap ty)
  | none => throw s!"Unknown identifier: {name}"

def translateBinOp (op : Operation) (e1 e2 : Core.Expression.Expr) : Except String Core.Expression.Expr :=
  let binOp bop := pure (LExpr.mkApp () bop [e1, e2])
  match op with
  | .And => binOp boolAndOp | .Or => binOp boolOrOp | .Implies => binOp boolImpliesOp
  | .Add => binOp intAddOp | .Sub => binOp intSubOp | .Mul => binOp intMulOp
  | .Div => binOp intDivOp | .Mod => binOp intModOp
  | .DivT => binOp Core.intDivTOp | .ModT => binOp Core.intModTOp
  | .StrConcat => binOp strConcatOp
  | .Lt => binOp intLtOp | .Leq => binOp intLeOp | .Gt => binOp intGtOp | .Geq => binOp intGeOp
  | .Eq => pure (.eq () e1 e2)
  | .Neq => pure (.app () boolNotOp (.eq () e1 e2))
  | _ => throw s!"translateBinOp: unsupported {repr op}"

def translateUnaryOp (op : Operation) (e : Core.Expression.Expr) : Except String Core.Expression.Expr :=
  match op with
  | .Not => pure (.app () boolNotOp e)
  | .Neg => pure (.app () intNegOp e)
  | _ => throw s!"translateUnaryOp: unsupported {repr op}"

macro "stmtexpr_wf " e:ident ", " h:ident : tactic =>
  `(tactic| (
    all_goals (cases $e:ident; subst $h:ident; simp_wf)
    all_goals first
      | omega
      | (have := List.sizeOf_lt_of_mem ‹_›; omega)))

def translateSimpleExpr (ctMap : ConstrainedTypeMap) (env : TypeEnv) (expr : StmtExprMd) : Except String Core.Expression.Expr :=
  match _h : expr.val with
  | .LiteralBool b => pure (.const () (.boolConst b))
  | .LiteralInt i => pure (.const () (.intConst i))
  | .LiteralString s => pure (.const () (.strConst s))
  | .Identifier name => do
      let ty ← lookupTypeWithCT ctMap env name
      pure (.fvar () ⟨name, ()⟩ (some ty))
  | .PrimitiveOp op [e] => do
      let e' ← translateSimpleExpr ctMap env e
      translateUnaryOp op e'
  | .PrimitiveOp op [e1, e2] => do
      let e1' ← translateSimpleExpr ctMap env e1
      let e2' ← translateSimpleExpr ctMap env e2
      translateBinOp op e1' e2'
  | .Forall _ _ _ => throw "Quantifiers not supported in constrained type constraints"
  | .Exists _ _ _ => throw "Quantifiers not supported in constrained type constraints"
  | _ => throw "Unsupported expression in constrained type constraint"
termination_by sizeOf expr
decreasing_by stmtexpr_wf expr, _h

def buildTranslatedConstraintMap (ctMap : ConstrainedTypeMap) : Except String TranslatedConstraintMap :=
  ctMap.foldM (init := {}) fun m _name ct => do
    let env : TypeEnv := [(ct.valueName, ct.base)]
    let coreExpr ← translateSimpleExpr ctMap env ct.constraint
    pure (m.insert ct.name { base := ct.base.val, valueName := ct.valueName, coreConstraint := coreExpr })

def varCloseByName (k : Nat) (x : Core.CoreIdent) (e : Core.Expression.Expr) : Core.Expression.Expr :=
  match e with
  | .const _ _ => e | .op _ _ _ => e
  | .bvar _ _ => e
  | .fvar m y yty => if x == y then .bvar m k else .fvar m y yty
  | .abs m ty e' => .abs m ty (varCloseByName (k + 1) x e')
  | .quant m qk ty tr e' => .quant m qk ty (varCloseByName (k + 1) x tr) (varCloseByName (k + 1) x e')
  | .app m e1 e2 => .app m (varCloseByName k x e1) (varCloseByName k x e2)
  | .ite m c t f => .ite m (varCloseByName k x c) (varCloseByName k x t) (varCloseByName k x f)
  | .eq m e1 e2 => .eq m (varCloseByName k x e1) (varCloseByName k x e2)

def injectQuantifierConstraint (ctMap : ConstrainedTypeMap) (tcMap : TranslatedConstraintMap)
    (isForall : Bool) (ty : HighTypeMd) (coreIdent : Core.CoreIdent) (closedBody : Core.Expression.Expr) : Core.Expression.Expr :=
  match ty.val with
  | .UserDefined typeName => match tcMap.get? typeName with
    | some tc =>
        let substConstraint := tc.coreConstraint.substFvar ⟨tc.valueName, ()⟩
          (.fvar () coreIdent (some (translateTypeWithCT ctMap ty)))
        let op := if isForall then boolImpliesOp else boolAndOp
        LExpr.mkApp () op [varCloseByName 0 coreIdent substConstraint, closedBody]
    | none => closedBody
  | _ => closedBody

def arrayTypeSynonym : Core.Decl := .type (.syn { name := "Array", typeArgs := ["T"], type := .tcons "Map" [.int, .ftvar "T"] })
/--
Translate Laurel StmtExpr to Core Expression using the `TranslateM` monad.
Diagnostics for disallowed constructs are emitted into the monad state.

`isPureContext` should be `true` when translating function bodies or contract expressions.
In that case, disallowed constructs emit `DiagnosticModel` errors into the state.
When `false` (inside a procedure body statement), disallowed constructs `panic!`
because `liftImperativeExpressions` should have already removed them.

`boundVars` tracks names bound by enclosing Forall/Exists quantifiers (innermost first).
When an Identifier matches a bound name at index `i`, it becomes `bvar i` (de Bruijn index)
instead of `fvar`.
-/

def normalizeCallee (callee : Identifier) : Identifier :=
  if callee.startsWith "«" && callee.endsWith "»" then
    (callee.drop 1 |>.dropEnd 1).toString
  else callee

structure SeqBounds where
  arr : Core.Expression.Expr := default
  start : Core.Expression.Expr := default
  «end» : Core.Expression.Expr := default

instance : Inhabited SeqBounds := ⟨{}⟩

def translateSimpleBound (expr : StmtExprMd) : Except String Core.Expression.Expr :=
  match expr.val with
  | .Identifier name => pure (.fvar () ⟨name, ()⟩ (some LMonoTy.int))
  | .LiteralInt i => pure (.const () (.intConst i))
  | _ => throw "Expected simple bound expression (identifier or literal)"

def translateSeqBounds (env : TypeEnv) (expr : StmtExprMd) : Except String SeqBounds :=
  match _h : expr.val with
  | .StaticCall callee [arg] =>
    let norm := normalizeCallee callee
    if norm == "Seq.From" then
      match arg.val with
      | .Identifier name =>
        match env.find? (fun (n, _) => n == name) with
        | some (_, ty) =>
          match ty.val with
          | .Applied ctor _ =>
            match ctor.val with
            | .UserDefined "Array" =>
              pure { arr := .fvar () ⟨name, ()⟩ none
                   , start := .const () (.intConst 0)
                   , «end» := .fvar () ⟨name ++ "_len", ()⟩ (some LMonoTy.int) }
            | _ => throw s!"Seq.From expects array, got {repr ty}"
          | _ => throw s!"Seq.From expects array, got {repr ty}"
        | none => throw s!"Unknown identifier in Seq.From: {name}"
      | _ => throw "Seq.From on complex expressions not supported"
    else throw s!"Not a sequence expression: {callee}"
  | .StaticCall callee [seq, bound] =>
    let norm := normalizeCallee callee
    if norm == "Seq.Take" then do
      let inner ← translateSeqBounds env seq
      let boundExpr ← translateSimpleBound bound
      pure { inner with «end» := boundExpr }
    else if norm == "Seq.Drop" then do
      let inner ← translateSeqBounds env seq
      let boundExpr ← translateSimpleBound bound
      pure { inner with start := boundExpr }
    else throw s!"Not a sequence expression: {callee}"
  | _ => throw "Not a sequence expression"
termination_by sizeOf expr
decreasing_by stmtexpr_wf expr, _h

def expandArrayArgs (env : TypeEnv) (args : List StmtExprMd) (translatedArgs : List Core.Expression.Expr) : List Core.Expression.Expr :=
  (args.zip translatedArgs).flatMap fun (arg, translated) =>
    match arg.val with
    | .Identifier arrName =>
      match env.find? (fun (n, _) => n == arrName) with
      | some (_, ty) =>
        match ty.val with
        | .Applied ctor _ =>
          match ctor.val with
          | .UserDefined "Array" => [translated, .fvar () ⟨arrName ++ "_len", ()⟩ (some LMonoTy.int)]
          | _ => [translated]
        | _ => [translated]
      | none => [translated]
    | _ => [translated]

def translateExpr (env : TypeEnv) (expr : StmtExprMd)
    (boundVars : List Identifier := []) (isPureContext : Bool := false)
    : TranslateM Core.Expression.Expr := do
  let s ← get
  let fieldNames := s.fieldNames
  let funcNames := s.funcNames
  -- Dummy expression used as placeholder when an error is emitted in pure context
  let dummy := .fvar () (⟨s!"DUMMY_VAR_{env.length}", ()⟩) none
  -- Emit an error in pure context; panic in impure context (lifting invariant violated)
  let disallowed (e : StmtExprMd) (msg : String) : TranslateM Core.Expression.Expr := do
    if isPureContext then
      emitDiagnostic (e.md.toDiagnostic msg)
      return dummy
    else
      panic! s!"translateExpr: {msg} (should have been lifted): {Std.Format.pretty (Std.ToFormat.format e)}"
  match h: expr.val with
  | .LiteralBool b => return .const () (.boolConst b)
  | .LiteralInt i => return .const () (.intConst i)
  | .LiteralString s => return .const () (.strConst s)
  | .Identifier name =>
      -- First check if this name is bound by an enclosing quantifier
      match boundVars.findIdx? (· == name) with
      | some idx =>
          -- Bound variable: use de Bruijn index
          return .bvar () idx
      | none =>
          -- Check if this is a field name (datatype constructor) or local variable
          if isFieldName fieldNames name then
            return .op () ⟨name, ()⟩ none
          else
            let s ← get
            return .fvar () ⟨name, ()⟩ (some (lookupType env name s.ctMap))
  | .PrimitiveOp op [e] =>
    match op with
    | .Not =>
      let re ← translateExpr env e boundVars isPureContext
      return .app () boolNotOp re
    | .Neg =>
      let re ← translateExpr env e boundVars isPureContext
      return .app () intNegOp re
    | _ => panic! s!"translateExpr: Invalid unary op: {repr op}"
  | .PrimitiveOp op [e1, e2] =>
    let re1 ← translateExpr env e1 boundVars isPureContext
    let re2 ← translateExpr env e2 boundVars isPureContext
    let binOp (bop : Core.Expression.Expr) : Core.Expression.Expr :=
      LExpr.mkApp () bop [re1, re2]
    match op with
    | .Eq => return .eq () re1 re2
    | .Neq => return .app () boolNotOp (.eq () re1 re2)
    | .And => return binOp boolAndOp
    | .Or => return binOp boolOrOp
    | .Implies => return binOp boolImpliesOp
    | .Add => return binOp intAddOp
    | .Sub => return binOp intSubOp
    | .Mul => return binOp intMulOp
    | .Div => return binOp intDivOp
    | .Mod => return binOp intModOp
    | .DivT => return binOp intDivTOp
    | .ModT => return binOp intModTOp
    | .Lt => return binOp intLtOp
    | .Leq => return binOp intLeOp
    | .Gt => return binOp intGtOp
    | .Geq => return binOp intGeOp
    | .StrConcat => return binOp strConcatOp
    | _ => panic! s!"translateExpr: Invalid binary op: {repr op}"
  | .PrimitiveOp op args =>
    panic! s!"translateExpr: PrimitiveOp {repr op} with {args.length} args"
  | .IfThenElse cond thenBranch elseBranch =>
      let bcond ← translateExpr env cond boundVars isPureContext
      let bthen ← translateExpr env thenBranch boundVars isPureContext
      let belse ← match elseBranch with
        | none => panic "if-then without else expression not yet implemented"
        | some e =>
            have : sizeOf e < sizeOf expr := by
              have := WithMetadata.sizeOf_val_lt expr
              cases expr; simp_all; omega
            translateExpr env e boundVars isPureContext
      return .ite () bcond bthen belse
  | .StaticCall name args =>
      -- Normalize callee name (strip «» quotes)
      let norm := if name.startsWith "«" && name.endsWith "»" then (name.drop 1 |>.dropEnd 1).toString else name
      -- In a pure context, only Core functions (not procedures) are allowed
      if isPureContext && !isCoreFunction funcNames norm && !norm.startsWith "Array." && !norm.startsWith "Seq." then
        disallowed expr "calls to procedures are not supported in functions or contracts"
      else if norm == "Array.Get" then do
        let translated ← args.attach.mapM (fun ⟨arg, _⟩ => translateExpr env arg boundVars isPureContext)
        match translated with
        | [arrExpr, idxExpr] =>
          let selectOp := LExpr.op () ⟨"select", ()⟩ none
          return LExpr.mkApp () selectOp [arrExpr, idxExpr]
        | _ => panic! s!"Array.Get expects 2 args, got {args.length}"
      else if norm == "Array.Length" then do
        match args with
        | [arrArg] =>
          match arrArg.val with
          | .Identifier arrName =>
            return .fvar () ⟨arrName ++ "_len", ()⟩ (some LMonoTy.int)
          | _ => panic! "Array.Length on complex expressions not supported"
        | _ => panic! s!"Array.Length expects 1 arg, got {args.length}"
      else if norm == "Seq.Contains" then do
        let translated ← args.attach.mapM (fun ⟨arg, _⟩ => translateExpr env arg boundVars isPureContext)
        match args, translated with
        | [seqArg, _], [_, targetExpr] =>
          let bounds : SeqBounds := match translateSeqBounds env seqArg with
            | .ok b => b
            | .error e => panic! s!"Seq.Contains: {e}"
          -- exists __q0 :: start <= __q0 && __q0 < end && arr[__q0] == target
          let qvar := LExpr.bvar () 0
          let selectOp := LExpr.op () ⟨"select", ()⟩ none
          let elemExpr := LExpr.mkApp () selectOp [bounds.arr, qvar]
          let inRange := LExpr.mkApp () boolAndOp [
            LExpr.mkApp () intLeOp [bounds.start, qvar],
            LExpr.mkApp () boolAndOp [
              LExpr.mkApp () intLtOp [qvar, bounds.«end»],
              .eq () elemExpr targetExpr]]
          return LExpr.exist () (some LMonoTy.int) inRange
        | _, _ => panic! s!"Seq.Contains expects 2 args, got {args.length}"
      else
        let fnOp : Core.Expression.Expr := .op () ⟨norm, ()⟩ none
        args.attach.foldlM (fun acc ⟨arg, _⟩ => do
          let re ← translateExpr env arg boundVars isPureContext
          return .app () acc re) fnOp
  | .Block [single] _ => translateExpr env single boundVars isPureContext
  | .Forall name ty body =>
      let s ← get
      let coreTy := translateTypeWithCT s.ctMap ty
      let coreBody ← translateExpr env body (name :: boundVars) isPureContext
      let coreIdent : Core.CoreIdent := ⟨name, ()⟩
      let closedBody := varCloseByName 0 coreIdent coreBody
      let injected := injectQuantifierConstraint s.ctMap s.tcMap true ty coreIdent closedBody
      return LExpr.all () (some coreTy) injected
  | .Exists name ty body =>
      let s ← get
      let coreTy := translateTypeWithCT s.ctMap ty
      let coreBody ← translateExpr env body (name :: boundVars) isPureContext
      let coreIdent : Core.CoreIdent := ⟨name, ()⟩
      let closedBody := varCloseByName 0 coreIdent coreBody
      let injected := injectQuantifierConstraint s.ctMap s.tcMap false ty coreIdent closedBody
      return LExpr.exist () (some coreTy) injected
  | .Hole => return dummy
  | .ReferenceEquals e1 e2 =>
      let re1 ← translateExpr env e1 boundVars isPureContext
      let re2 ← translateExpr env e2 boundVars isPureContext
      return .eq () re1 re2
  | .Assign _ _ =>
      disallowed expr "destructive assignments are not supported in functions or contracts"
  | .While _ _ _ _ =>
      disallowed expr "loops are not supported in functions or contracts"
  | .Exit _ => disallowed expr "exit is not supported in expression position"

  | .IsType _ _ => panic "IsType should have been lowered"
  | .New _ => panic! s!"New should have been eliminated by typeHierarchyTransform"
  | .FieldSelect target fieldName =>
      -- Field selects should have been eliminated by heap parameterization
      -- If we see one here, it's an error in the pipeline
      panic! s!"FieldSelect should have been eliminated by heap parameterization: {Std.ToFormat.format target}#{fieldName}"
  | .Block _ _ => panic "block expression not yet implemented (should be lowered in a separate pass)"
  | .LocalVariable _ _ _ => panic "local variable expression not yet implemented (should be lowered in a separate pass)"
  | .Return _ => disallowed expr "return expression not yet implemented (should be lowered in a separate pass)"

  | .AsType target _ => panic "AsType expression not implemented"
  | .Assigned _ => panic "assigned expression not implemented"
  | .Old value => panic "old expression not implemented"
  | .Fresh _ => panic "fresh expression not implemented"
  | .Assert _ => panic "assert expression not implemented"
  | .Assume _ => panic "assume expression not implemented"
  | .ProveBy value _ => panic "proveBy expression not implemented"
  | .ContractOf _ _ => panic "contractOf expression not implemented"
  | .Abstract => panic "abstract expression not implemented"
  | .All => panic "all expression not implemented"
  | .InstanceCall _ _ _ => panic "InstanceCall not implemented"
  | .PureFieldUpdate _ _ _ => panic "This expression not implemented"
  | .This => panic "This expression not implemented"
  termination_by expr
  decreasing_by
    all_goals first
      | (have := WithMetadata.sizeOf_val_lt expr; term_by_mem)
      | (simp_wf; have := WithMetadata.sizeOf_val_lt expr; omega)

def getNameFromMd (md : Imperative.MetaData Core.Expression): String :=
  let fileRange := (Imperative.getFileRange md).getD (panic "getNameFromMd bug")
  s!"({fileRange.range.start})"


def genConstraintCheck (ctMap : ConstrainedTypeMap) (tcMap : TranslatedConstraintMap) (param : Parameter) : Option Core.Expression.Expr :=
  match param.type.val with
  | .UserDefined name =>
    match tcMap.get? name with
    | some tc =>
      let paramIdent : Core.CoreIdent := ⟨param.name, ()⟩
      let valueIdent : Core.CoreIdent := ⟨tc.valueName, ()⟩
      let baseTy := translateTypeWithCT ctMap param.type
      some (tc.coreConstraint.substFvar valueIdent (.fvar () paramIdent (some baseTy)))
    | none => none
  | _ => none

def genConstraintAssert (ctMap : ConstrainedTypeMap) (tcMap : TranslatedConstraintMap) (name : Identifier) (ty : HighTypeMd) (md : Imperative.MetaData Core.Expression) : List Core.Statement :=
  match genConstraintCheck ctMap tcMap { name, type := ty } with
  | some expr => [Core.Statement.assert s!"{name}_constraint" expr md]
  | none => []
def defaultExprForType (ctMap : ConstrainedTypeMap) (ty : HighTypeMd) : Core.Expression.Expr :=
  let resolved := resolveBaseType ctMap ty.val
  match resolved with
  | .TInt => .const () (.intConst 0)
  | .TBool => .const () (.boolConst false)
  | .TString => .const () (.strConst "")
  | _ =>
    let coreTy := translateType ⟨resolved, ty.md⟩
    .fvar () (⟨"$default", ()⟩) (some coreTy)


def getArrayElemConstrainedType (env : TypeEnv) (arr : StmtExprMd) : Option Identifier :=
  match arr.val with
  | .Identifier name =>
    if let some (_, { val := .Applied { val := .UserDefined "Array", ..} [{ val := .UserDefined elemName, ..}], ..}) := env.find? (fun (n, _) => n == name) then
      some elemName
    else none
  | _ => none

def collectConstrainedArrayAccesses (env : TypeEnv) (tcMap : TranslatedConstraintMap) (e : StmtExprMd) : List (StmtExprMd × StmtExprMd × TranslatedConstraint) :=
  match _h : e.val with
  | .StaticCall callee [arr, idx] =>
    let sub := collectConstrainedArrayAccesses env tcMap arr ++ collectConstrainedArrayAccesses env tcMap idx
    if normalizeCallee callee == "Array.Get" then
      match getArrayElemConstrainedType env arr >>= tcMap.get? with
      | some tc => (arr, idx, tc) :: sub
      | none => sub
    else sub
  | .PrimitiveOp _ args | .StaticCall _ args =>
    args.attach.flatMap fun ⟨a, _⟩ => collectConstrainedArrayAccesses env tcMap a
  | .IfThenElse c t el =>
    collectConstrainedArrayAccesses env tcMap c ++
    collectConstrainedArrayAccesses env tcMap t ++
    (match el with | some x => collectConstrainedArrayAccesses env tcMap x | none => [])
  | .Assign ts v =>
    ts.attach.flatMap (fun ⟨a, _⟩ => collectConstrainedArrayAccesses env tcMap a) ++
    collectConstrainedArrayAccesses env tcMap v
  | .Assert cond | .Assume cond =>
    collectConstrainedArrayAccesses env tcMap cond
  | .Return (some v) =>
    collectConstrainedArrayAccesses env tcMap v
  | .LocalVariable _ _ (some init) =>
    collectConstrainedArrayAccesses env tcMap init
  | _ => []
termination_by sizeOf e
decreasing_by stmtexpr_wf e, _h

def genArrayElemAssumes (tcMap : TranslatedConstraintMap) (env : TypeEnv) (expr : StmtExprMd)
    (translateExprFn : StmtExprMd → TranslateM Core.Expression.Expr) : TranslateM (List Core.Statement) := do
  let accesses := collectConstrainedArrayAccesses env tcMap expr
  accesses.mapM fun (arr, idx, tc) => do
    let arrExpr ← translateExprFn arr
    let idxExpr ← translateExprFn idx
    let selectExpr := LExpr.mkApp () (LExpr.op () ⟨"select", ()⟩ none) [arrExpr, idxExpr]
    let constraintExpr := tc.coreConstraint.substFvar ⟨tc.valueName, ()⟩ selectExpr
    pure (Core.Statement.assume "array_elem_constraint" constraintExpr expr.md)

/--
Translate Laurel StmtExpr to Core Statements using the `TranslateM` monad.
Diagnostics are emitted into the monad state.
-/
def translateStmt (env : TypeEnv) (outputParams : List Parameter) (stmt : StmtExprMd)
    : TranslateM (TypeEnv × List Core.Statement) := do
  let s ← get
  let functionNames := s.funcNames
  let md := stmt.md
  let arrayElemAssumes ← genArrayElemAssumes s.tcMap env stmt (translateExpr env · [] true)
  -- Note: cases use `pure` not `return` because `return` would exit translateStmt,
  -- bypassing the arrayElemAssumes prepend below.
  let (env', stmts) ← match _h : stmt.val with
  | @StmtExpr.Assert cond =>
      -- Assert/assume bodies must be pure expressions (no assignments, loops, or procedure calls)
      let coreExpr ← translateExpr env cond [] (isPureContext := true)
      pure (env, [Core.Statement.assert ("assert" ++ getNameFromMd md) coreExpr md])
  | @StmtExpr.Assume cond =>
      let coreExpr ← translateExpr env cond [] (isPureContext := true)
      pure (env, [Core.Statement.assume ("assume" ++ getNameFromMd md) coreExpr md])
  | .Block stmts _ =>
      let (env', stmtsList) ← stmts.attach.foldlM (fun (e, acc) ⟨s, _hs⟩ => do
        let (e', ss) ← translateStmt e outputParams s
        return (e', acc ++ ss)) (env, [])
      pure (env', stmtsList)
  | .LocalVariable name ty initializer =>
      let s ← get
      let env' := (name, ty) :: env
      let boogieMonoType := translateTypeWithCT s.ctMap ty
      let boogieType := LTy.forAll [] boogieMonoType
      let ident := ⟨name, ()⟩
      match initializer with
      | some (⟨ .StaticCall callee args, callMd⟩) =>
          -- Check if this is a function or a procedure call
          if isCoreFunction functionNames callee then
            -- Translate as expression (function application)
            let boogieExpr ← translateExpr env (⟨ .StaticCall callee args, callMd ⟩)
            let cc := genConstraintAssert s.ctMap s.tcMap name ty md
            pure (env', [Core.Statement.init ident boogieType (some boogieExpr) md] ++ cc)
          else
            -- Translate as: var name; call name := callee(args)
            let coreArgs ← args.mapM (fun a => translateExpr env a)
            let defaultExpr := defaultExprForType (← get).ctMap ty
            let initStmt := Core.Statement.init ident boogieType (some defaultExpr) md
            let callStmt := Core.Statement.call [ident] callee (expandArrayArgs env args coreArgs) md
            let cc := genConstraintAssert s.ctMap s.tcMap name ty md
            pure (env', [initStmt, callStmt] ++ cc)
      | some initExpr =>
          let coreExpr ← translateExpr env initExpr
          let cc := genConstraintAssert s.ctMap s.tcMap name ty md
          pure (env', [Core.Statement.init ident boogieType (some coreExpr) md] ++ cc)
      | none =>
          let defaultExpr := defaultExprForType (← get).ctMap ty
          let cc := genConstraintAssert s.ctMap s.tcMap name ty md
          pure (env', [Core.Statement.init ident boogieType (some defaultExpr) md] ++ cc)
  | .Assign targets value =>
      match targets with
      | [⟨ .Identifier name, _ ⟩] =>
          let ident := ⟨name, ()⟩
          -- Check if RHS is a procedure call (not a function)
          match value.val with
          | .StaticCall callee args =>
              if isCoreFunction functionNames callee then
                -- Functions are translated as expressions
                let boogieExpr ← translateExpr env value
                pure (env, [Core.Statement.set ident boogieExpr md])
              else
                -- Procedure calls need to be translated as call statements
                let coreArgs ← args.mapM (fun a => translateExpr env a)
                pure (env, [Core.Statement.call [ident] callee (expandArrayArgs env args coreArgs) md])
          | _ =>
              let boogieExpr ← translateExpr env value
              pure (env, [Core.Statement.set ident boogieExpr md])
      | _ =>
          -- Parallel assignment: (var1, var2, ...) := expr
          -- Example use is heap-modifying procedure calls: (result, heap) := f(heap, args)
          match value.val with
          | .StaticCall callee args =>
              let coreArgs ← args.mapM (fun a => translateExpr env a)
              let lhsIdents := targets.filterMap fun t =>
                match t.val with
                | .Identifier name => some (⟨name, ()⟩)
                | _ => none
              pure (env, [Core.Statement.call lhsIdents callee (expandArrayArgs env args coreArgs) value.md])
          | _ =>
              panic "Assignments with multiple target but without a RHS call should not be constructed"
  | .IfThenElse cond thenBranch elseBranch =>
      let bcond ← translateExpr env cond
      let (_, bthen) ← translateStmt env outputParams thenBranch
      let belse ← match elseBranch with
                  | some e => (·.2) <$> translateStmt env outputParams e
                  | none => pure []
      pure (env, [Imperative.Stmt.ite bcond bthen belse .empty])
  | .StaticCall name args =>
      -- Check if this is a function or procedure
      if isCoreFunction functionNames name then
        -- Functions as statements have no effect (shouldn't happen in well-formed programs)
        pure (env, [])
      else
        let coreArgs ← args.mapM (fun a => translateExpr env a)
        pure (env, [Core.Statement.call [] name (expandArrayArgs env args coreArgs) md])
  | .Return valueOpt =>
      match valueOpt, outputParams.head? with
      | some value, some outParam =>
          let ident := ⟨outParam.name, ()⟩
          let coreExpr ← translateExpr env value
          let assignStmt := Core.Statement.set ident coreExpr md
          let noFallThrough := Core.Statement.assume "return" (.const () (.boolConst false)) .empty
          pure (env, [assignStmt, noFallThrough])
      | none, _ =>
          let noFallThrough := Core.Statement.assume "return" (.const () (.boolConst false)) .empty
          pure (env, [noFallThrough])
      | some _, none =>
          panic! "Return statement with value but procedure has no output parameters"
  | .While cond invariants decreasesExpr body =>
      let condExpr ← translateExpr env cond
      let invExprs ← invariants.mapM (translateExpr env)
      let decreasingExprCore ← decreasesExpr.mapM (translateExpr env)
      let (_, bodyStmts) ← translateStmt env outputParams body
      pure (env, [Imperative.Stmt.loop condExpr decreasingExprCore invExprs bodyStmts md])
  | _ => pure (env, [])
  return (env', arrayElemAssumes ++ stmts)  termination_by sizeOf stmt
  decreasing_by
    all_goals
      have hlt := WithMetadata.sizeOf_val_lt stmt
      cases stmt; term_by_mem

/--
Translate a list of checks (preconditions or postconditions) to Core checks.
Each check gets a label like `"requires"` or `"requires_0"`, `"requires_1"`, etc.
-/
private def translateChecks (env : TypeEnv) (checks : List StmtExprMd) (labelBase : String)
    : TranslateM (ListMap Core.CoreLabel Core.Procedure.Check) :=
  checks.mapIdxM (fun i check => do
    let label := if checks.length == 1 then labelBase else s!"{labelBase}_{i}"
    let checkExpr ← translateExpr env check [] (isPureContext := true)
    let c : Core.Procedure.Check := { expr := checkExpr, md := check.md }
    return (label, c))

/--
Translate Laurel Parameter to Core Signature entry
-/
def translateParameterToCore (param : Parameter) : TranslateM (Core.CoreIdent × LMonoTy) := do
  let s ← get
  let ident := ⟨param.name, ()⟩
  let ty := translateTypeWithCT s.ctMap param.type
  return (ident, ty)

def expandArrayParam (param : Parameter) : TranslateM (List (Core.CoreIdent × LMonoTy)) := do
  let base ← translateParameterToCore param
  match param.type.val with
  | .Applied ctor _ =>
    match ctor.val with
    | .UserDefined "Array" =>
      return [base, (⟨param.name ++ "_len", ()⟩, LMonoTy.int)]
    | _ => return [base]
  | _ => return [base]

/--
Translate Laurel Procedure to Core Procedure using `TranslateM`.
Diagnostics from disallowed constructs in preconditions, postconditions, and body
are emitted into the monad state.
-/
def translateProcedure (proc : Procedure) : TranslateM Core.Procedure := do
  let inputPairs := (← proc.inputs.mapM expandArrayParam).flatten
  let inputs := inputPairs
  let outputs := ← proc.outputs.mapM translateParameterToCore
  let header : Core.Procedure.Header := {
    name := proc.name
    typeArgs := []
    inputs := inputs
    outputs := outputs
  }
  let initEnv : TypeEnv := proc.inputs.map (fun p => (p.name, p.type)) ++
                           proc.outputs.map (fun p => (p.name, p.type))
  -- Translate preconditions
  let preconditions ← translateChecks initEnv proc.preconditions "requires"
  -- Add constraint checks for input parameters
  let s ← get
  let inputConstraints : ListMap Core.CoreLabel Core.Procedure.Check :=
    proc.inputs.filterMap fun p =>
      match genConstraintCheck s.ctMap s.tcMap p with
      | some expr => some (s!"{p.name}_constraint", { expr, md := p.type.md })
      | none => none
  let preconditions := inputConstraints ++ preconditions

  -- Translate postconditions for Opaque bodies
  let postconditions : ListMap Core.CoreLabel Core.Procedure.Check ←
    match proc.body with
    | .Opaque postconds _ _ =>
        translateChecks initEnv postconds "postcondition"
    | _ => pure []
  -- Add output parameter constraints as postconditions
  let outputConstraints : ListMap Core.CoreLabel Core.Procedure.Check :=
    proc.outputs.filterMap fun p =>
      match genConstraintCheck s.ctMap s.tcMap p with
      | some expr => some (s!"{p.name}_constraint", { expr, md := p.type.md })
      | none => none
  let postconditions := postconditions ++ outputConstraints
  let modifies : List Core.Expression.Ident := []
  let body : List Core.Statement ←
    match proc.body with
    | .Transparent bodyExpr => (·.2) <$> translateStmt initEnv proc.outputs bodyExpr
    | .Opaque _postconds (some impl) _ => (·.2) <$> translateStmt initEnv proc.outputs impl
    | _ => pure [Core.Statement.assume "no_body" (.const () (.boolConst false)) .empty]
  let spec : Core.Procedure.Spec := { modifies, preconditions, postconditions }
  return { header, spec, body }

/--
Check if a Laurel expression is pure (contains no side effects).
Used to determine if a procedure can be translated as a Core function.
-/
private def isPureExpr(expr: StmtExprMd): Bool :=
  match _h : expr.val with
  | .LiteralBool _ => true
  | .LiteralInt _ => true
  | .LiteralString _ => true
  | .Identifier _ => true
  | .PrimitiveOp _ args => args.attach.all (fun ⟨a, _⟩ => isPureExpr a)
  | .IfThenElse c t none => isPureExpr c && isPureExpr t
  | .IfThenElse c t (some e) => isPureExpr c && isPureExpr t && isPureExpr e
  | .StaticCall _ args => args.attach.all (fun ⟨a, _⟩ => isPureExpr a)
  | .New _ => false
  | .ReferenceEquals e1 e2 => isPureExpr e1 && isPureExpr e2
  | .Block [single] _ => isPureExpr single
  | .Block _ _ => false
  -- Statement-like
  | .LocalVariable .. => true
  | .While .. => false
  | .Exit .. => false
  | .Return .. => false
  -- Expression-like
  | .Assign .. => false
  | .FieldSelect .. => true
  | .PureFieldUpdate .. => true
  -- Instance related
  | .This => panic s!"isPureExpr not implemented for This"
  | .AsType .. => panic s!"isPureExpr not supported for AsType"
  | .IsType .. => panic s!"isPureExpr not supported for IsType"
  | .InstanceCall .. => panic s!"isPureExpr not implemented for InstanceCall"
  -- Verification specific
  | .Forall .. => panic s!"isPureExpr not implemented for Forall"
  | .Exists .. => panic s!"isPureExpr not implemented for Exists"
  | .Assigned .. => panic s!"isPureExpr not supported for AsType"
  | .Old .. => panic s!"isPureExpr not supported for AsType"
  | .Fresh .. => panic s!"isPureExpr not supported for AsType"
  | .Assert .. => panic s!"isPureExpr not implemented for Assert"
  | .Assume .. => panic s!"isPureExpr not implemented for Assume"
  | .ProveBy .. => panic s!"isPureExpr not implemented for ProveBy"
  | .ContractOf .. => panic s!"isPureExpr not implemented for ContractOf"
  | .Abstract => panic s!"isPureExpr not implemented for Abstract"
  | .All => panic s!"isPureExpr not implemented for All"
  -- Dynamic / closures
  | .Hole => true
  termination_by sizeOf expr
  decreasing_by all_goals (have := WithMetadata.sizeOf_val_lt expr; term_by_mem)

/-- Check if a pure-marked procedure can actually be represented as a Core function:
    transparent body that is a pure expression and has exactly one output. -/
private def canBeCoreFunctionBody (proc : Procedure) : Bool :=
  match proc.body with
  | .Transparent bodyExpr =>
    isPureExpr bodyExpr &&
    proc.outputs.length == 1
  | .Opaque _ bodyExprOption _ =>
    (bodyExprOption.map isPureExpr).getD true &&
    proc.outputs.length == 1
  | _ => false

/--
Translate a Laurel Procedure to a Core Function (when applicable) using `TranslateM`.
Diagnostics for disallowed constructs in the function body are emitted into the monad state.
-/
def translateProcedureToFunction (proc : Procedure) : TranslateM Core.Decl := do
  let inputs := (← proc.inputs.mapM expandArrayParam).flatten
  let s ← get
  let outputTy := match proc.outputs.head? with
    | some p => translateTypeWithCT s.ctMap p.type
    | none => LMonoTy.int
  let initEnv : TypeEnv := proc.inputs.map (fun p => (p.name, p.type))
  -- Translate precondition to FuncPrecondition (skip trivial `true`)
  let preconditions ← proc.preconditions.mapM (fun precondition => do
    let checkExpr ← translateExpr initEnv precondition [] true
    return { expr := checkExpr, md := () })

  let body ← match proc.body with
    | .Transparent bodyExpr => some <$> translateExpr initEnv bodyExpr [] (isPureContext := true)
    | .Opaque _ (some bodyExpr) _ =>
      emitDiagnostic (proc.md.toDiagnostic "functions with postconditions are not yet supported")
      some <$> translateExpr initEnv bodyExpr [] (isPureContext := true)
    | _ => pure none
  return .func {
    name := ⟨proc.name, ()⟩
    typeArgs := []
    inputs := inputs
    output := outputTy
    body := body
    preconditions := preconditions
  }

/--
Translate a Laurel DatatypeDefinition to a Core type declaration.
Zero constructors produces an opaque (abstract) type; otherwise a Core datatype.
-/
def translateDatatypeDefinition (dt : DatatypeDefinition) : Core.Decl :=
  match h : dt.constructors with
  | [] =>
    -- Zero constructors: opaque type
    Core.Decl.type (.con { name := dt.name, numargs := dt.typeArgs.length })
  | first :: rest =>
    let constrs : List (Lambda.LConstr Unit) := (first :: rest).map fun c =>
      { name := ⟨c.name, ()⟩
        args := c.args.map fun (n, ty) => (⟨n, ()⟩, translateType ty) }
    let ldt : Lambda.LDatatype Unit := {
      name := dt.name
      typeArgs := dt.typeArgs
      constrs := constrs
      constrs_ne := by simp [constrs]
    }
    Core.Decl.type (.data [ldt])

/--
Try to translate a Laurel Procedure marked `isFunctional` to a Core Function.
Returns `.error` with diagnostics if the procedure body contains disallowed constructs
(destructive assignments, loops, or procedure calls).
-/
def tryTranslatePureToFunction (proc : Procedure) (initState : TranslateState)
    : Except (Array DiagnosticModel) Core.Decl :=
  let (decl, finalState) := runTranslateM initState (translateProcedureToFunction proc)
  if finalState.diagnostics.isEmpty then
    .ok decl
  else
    .error finalState.diagnostics.toArray

/--
Translate Laurel Program to Core Program
-/

def translate (program : Program) : Except (Array DiagnosticModel) (Core.Program × Array DiagnosticModel) := do
  let program := heapParameterization program
  let program := typeHierarchyTransform program
  let (program, modifiesDiags) := modifiesClausesTransform program
  dbg_trace "===  Program after heapParameterization + modifiesClausesTransform ==="
  dbg_trace (toString (Std.Format.pretty (Std.ToFormat.format program)))
  dbg_trace "================================="
  let program := liftImperativeExpressions program
  -- Build constrained type maps
  let ctMap := buildConstrainedTypeMap program.types
  let tcMap ← (buildTranslatedConstraintMap ctMap).mapError fun e => #[{ fileRange := default, message := e }]
  -- Collect field names from the Field datatype (generated by heapParameterization)
  let fieldNames : List Identifier := program.types.foldl (fun acc td =>
    match td with
    | .Datatype dt => if dt.name == "Field" then acc ++ dt.constructors.map (·.name) else acc
    | _ => acc) []

  -- Procedures marked isFunctional are translated to Core functions; all others become Core procedures.
  let (markedPure, procProcs) := program.staticProcedures.partition (·.isFunctional)
  -- Build the shared initial state with constants and function names
  let funcNames : FunctionNames := markedPure.map (·.name)
  let initState : TranslateState := { fieldNames := fieldNames, funcNames, ctMap, tcMap }
  -- Try to translate each isFunctional procedure to a Core function, collecting errors for failures
  let (pureErrors, pureFuncDecls) := markedPure.foldl (fun (errs, decls) p =>
    match tryTranslatePureToFunction p initState with
    | .error es => (errs ++ es.toList, decls)
    | .ok d     => (errs, decls.push d)) ([], #[])
  -- Translate procedures using the monad, collecting diagnostics from the final state
  let (procedures, procState) := runTranslateM initState do
    procProcs.mapM translateProcedure
  let procDiags := procState.diagnostics

  -- Translate Laurel constants to Core function declarations (0-ary functions)
  let (constantDecls, constantsState) := runTranslateM initState $ program.constants.mapM fun c => do
    let coreTy := translateTypeWithCT (← get).ctMap c.type
    let body ← c.initializer.mapM (translateExpr [] ·)
    return Core.Decl.func {
      name := ⟨c.name, ()⟩
      typeArgs := []
      inputs := []
      output := coreTy
      body := body
    }

  -- Collect ALL errors from both functions and procedures before deciding whether to fail
  let allErrors := pureErrors ++ procDiags ++ constantsState.diagnostics
  if !allErrors.isEmpty then
    .error allErrors.toArray
  let procDecls := procedures.map (fun p => Core.Decl.proc p .empty)

  -- Filter out the Field and TypeTag opaque types. These are only in the prelude to satisfy the DDM type checker.
  let preludeDecls := corePrelude.decls.filter fun d =>
    d.name.name != "Field" && d.name.name != "TypeTag"

  -- Translate Laurel datatype definitions to Core datatype declarations
  let laurelDatatypeDecls := program.types.filterMap fun td => match td with
    | .Datatype dt => some (translateDatatypeDefinition dt)
    | _ => none
  pure ({ decls := laurelDatatypeDecls ++ preludeDecls ++ [arrayTypeSynonym] ++ constantDecls ++ pureFuncDecls.toList ++ procDecls }, modifiesDiags)

/--
Verify a Laurel program using an SMT solver
-/
def verifyToVcResults (program : Program)
    (options : VerifyOptions := .default)
    : IO (Except (Array DiagnosticModel) VCResults) := do
  let (strataCoreProgram, translateDiags) ← match translate program with
    | .error translateErrorDiags => return .error translateErrorDiags
    | .ok result => pure result

  -- Enable removeIrrelevantAxioms to avoid polluting simple assertions with heap axioms
  let options := { options with removeIrrelevantAxioms := true }
  -- Debug: Print the generated Strata Core program
  dbg_trace "=== Generated Strata Core Program ==="
  dbg_trace (toString (Std.Format.pretty (Strata.Core.formatProgram strataCoreProgram) 100))
  dbg_trace "================================="
  let runner tempDir :=
    EIO.toIO (fun f => IO.Error.userError (toString f))
        (Core.verify strataCoreProgram tempDir .none options)
  let ioResult ← match options.vcDirectory with
    | .none => IO.FS.withTempDir runner
    | .some p => IO.FS.createDirAll ⟨p.toString⟩; runner ⟨p.toString⟩
  if translateDiags.isEmpty then
    return .ok ioResult
  else
    return .error (translateDiags ++ ioResult.filterMap toDiagnosticModel)


def verifyToDiagnostics (files: Map Strata.Uri Lean.FileMap) (program : Program)
    (options : VerifyOptions := .default): IO (Array Diagnostic) := do
  -- Validate for diamond-inherited field accesses before translation
  let uri := files.keys.head!
  let diamondErrors := validateDiamondFieldAccesses uri program
  if !diamondErrors.isEmpty then
    return diamondErrors.map (fun dm => dm.toDiagnostic files)
  let results <- verifyToVcResults program options
  match results with
  | .error errors => return errors.map (fun dm => dm.toDiagnostic files)
  | .ok results => return results.filterMap (fun dm => dm.toDiagnostic files)


def verifyToDiagnosticModels (program : Program) (options : VerifyOptions := .default) : IO (Array DiagnosticModel) := do
  let results <- verifyToVcResults program options
  match results with
  | .error errors => return errors
  | .ok results => return results.filterMap toDiagnosticModel

end Laurel
