// core_st tree-sitter grammar.
// AUTO-GENERATED from the Strata DDM grammar.
// Do not edit by hand; run: lake env lean --run editors/GenSyntax.lean treesitter
// LR conflicts are loaded from conflicts.json; (re)generate it with:
//   node resolve-conflicts.cjs

const fs = require('fs');
const path = require('path');
let CONFLICTS = [];
try { CONFLICTS = JSON.parse(fs.readFileSync(path.join(__dirname, 'conflicts.json'), 'utf8')); }
catch (e) { /* no conflicts.json yet: run resolve-conflicts.cjs */ }

function commaSep(rule) { return optional(seq(rule, repeat(seq(',', rule)))); }
function semiSep(rule) { return optional(seq(rule, repeat(seq(';', rule)))); }

module.exports = grammar({
  name: 'core_st',

  extras: $ => [/\s/, $.comment],
  word: $ => $.identifier,
  conflicts: $ => CONFLICTS.map(group => group.map(name => $[name])),

  rules: {
    source_file: $ => seq(optional($.program_header), repeat($._command)),
    program_header: $ => seq('program', $.identifier, ';'),
    _command: $ => choice($.command_procedure, $.command_typedecl, $.command_typesynonym, $.command_constdecl, $.command_fndecl, $.command_fndef, $.command_recfndefs, $.command_axiom, $.command_distinct, $.command_block, $.command_datatypes),
    _type_var: $ => $.identifier,
    _type_args: $ => $.type_args,
    _bind: $ => $.bind_mk,
    _decl_list: $ => choice($._bind, $.decl_push),
    _mono_bind: $ => $.mono_bind_mk,
    _mono_decl_list: $ => choice($._mono_bind, $.mono_decl_push),
    _trigger_group: $ => $.trigger,
    _triggers: $ => choice($._trigger_group, $.triggers_push),
    _lhs: $ => choice($.identifier, $.lhs_array),
    _statement: $ => choice($.var_statement, $.init_statement, $.assign, $.assume, $.assert, $.cover, $.if_statement, $.havoc_statement, $.while_statement, $.call_statement, $.block_statement, $.exit_statement, $.func_decl_statement, $.type_decl_statement),
    _block: $ => $.block,
    _else: $ => $.else1,
    _label: $ => $.label,
    _reach_check: $ => $.reach_check,
    _expr_or_nondet: $ => choice($.cond_det, $.cond_nondet),
    _invariant: $ => $.invariant,
    _invariants: $ => $.cons_invariants,
    _measure: $ => $.measure_mk,
    _call_arg: $ => choice($._expr, $.call_arg_out, $.call_arg_inout),
    _spec_elt: $ => choice($.ensures_spec, $.requires_spec),
    _free: $ => $.free,
    _spec: $ => $.spec_mk,
    _binding: $ => choice($.mk_binding, $.out_binding, $.inout_binding, $.cases_binding),
    _bindings: $ => $.mk_bindings,
    _inline: $ => $.inline,
    _rec_fn_decl: $ => $.recfn_decl,
    _constructor: $ => $.constructor_mk,
    _constructor_list: $ => choice($.constructor_list_atom, $.constructor_list_push),
    _datatype_decl: $ => $.datatype_decl,
    type_args: $ => seq('<', commaSep($._type_var), '>'),
    bind_mk: $ => seq($.identifier, ':', optional($._type_args), $._type),
    decl_push: $ => prec.left(1024, seq($._decl_list, ',', $._bind)),
    mono_bind_mk: $ => prec.left(1024, seq($.identifier, ':', $._type)),
    mono_decl_push: $ => prec.left(1024, seq($._mono_decl_list, ',', $._mono_bind)),
    trigger: $ => seq('{', commaSep($._expr), '}'),
    triggers_push: $ => seq($._triggers, $._trigger_group),
    lhs_array: $ => seq($._lhs, '[', $._expr, ']'),
    label: $ => seq('[', $.identifier, ']:'),
    reach_check: $ => '@[reachCheck]',
    var_statement: $ => seq('var', $._decl_list, ';'),
    init_statement: $ => seq('var', $.identifier, ':', $._type, ':=', $._expr, ';'),
    assign: $ => seq($._lhs, ':=', $._expr, ';'),
    assume: $ => seq('assume', optional($._label), $._expr, ';'),
    assert: $ => seq(optional($._reach_check), 'assert', optional($._label), $._expr, ';'),
    cover: $ => seq(optional($._reach_check), 'cover', optional($._label), $._expr, ';'),
    cond_det: $ => seq('(', $._expr, ')'),
    cond_nondet: $ => '*',
    if_statement: $ => seq('if', $._expr_or_nondet, $._block, optional($._else)),
    else1: $ => prec.right(1024, seq('else', $._block)),
    havoc_statement: $ => seq('havoc', $.identifier, ';'),
    invariant: $ => seq('invariant', optional($._label), $._expr, ';'),
    cons_invariants: $ => seq('invariant', optional($._label), $._expr, optional($._invariants)),
    measure_mk: $ => seq('decreases', $._expr),
    while_statement: $ => seq('while', $._expr_or_nondet, optional($._measure), optional($._invariants), $._block),
    call_arg_out: $ => prec.right(1024, seq('out', $.identifier)),
    call_arg_inout: $ => prec.right(1024, seq('inout', $.identifier)),
    call_statement: $ => seq('call', $.identifier, '(', commaSep($._call_arg), ')', ';'),
    block: $ => seq('{', repeat($._statement), '}'),
    block_statement: $ => prec.right(1024, seq($.identifier, ':', $._block)),
    exit_statement: $ => seq('exit', $.identifier, ';'),
    free: $ => 'free',
    ensures_spec: $ => seq(optional($._free), 'ensures', optional($._label), $._expr, ';'),
    requires_spec: $ => seq(optional($._free), 'requires', optional($._label), $._expr, ';'),
    spec_mk: $ => seq('spec', '{', repeat($._spec_elt), '}'),
    mk_binding: $ => prec.right(40, seq($.identifier, ':', $._type)),
    out_binding: $ => seq('out', $.identifier, ':', $._type),
    inout_binding: $ => seq('inout', $.identifier, ':', $._type),
    cases_binding: $ => seq('@[cases]', $.identifier, ':', $._type),
    mk_bindings: $ => seq('(', commaSep($._binding), ')'),
    command_procedure: $ => seq('procedure', $.identifier, optional($._type_args), $._bindings, optional($._spec), optional($._block), ';'),
    command_typedecl: $ => seq('type', $.identifier, optional($._bindings), ';'),
    command_typesynonym: $ => seq('type', $.identifier, optional($._bindings), ':=', optional($._type_args), $._type, ';'),
    command_constdecl: $ => seq('const', $.identifier, ':', optional($._type_args), $._type, ';'),
    command_fndecl: $ => seq('function', $.identifier, optional($._type_args), $._bindings, ':', $._type, ';'),
    inline: $ => 'inline',
    command_fndef: $ => seq(optional($._inline), 'function', $.identifier, optional($._type_args), $._bindings, ':', $._type, repeat($._spec_elt), '{', $._expr, '}'),
    recfn_decl: $ => seq('function', $.identifier, optional($._type_args), $._bindings, ':', $._type, repeat($._spec_elt), optional($._measure), '{', $._expr, '}'),
    command_recfndefs: $ => seq('rec', repeat($._rec_fn_decl), ';'),
    func_decl_statement: $ => seq(optional($._inline), 'function', $.identifier, optional($._type_args), $._bindings, ':', $._type, repeat($._spec_elt), '{', $._expr, '}'),
    type_decl_statement: $ => seq('type', $.identifier, optional($._bindings), ';'),
    command_axiom: $ => seq('axiom', optional($._label), $._expr, ';'),
    command_distinct: $ => seq('distinct', optional($._label), '[', commaSep($._expr), ']', ';'),
    command_block: $ => seq($._block, ';'),
    constructor_mk: $ => seq($.identifier, '(', optional(commaSep($._binding)), ')'),
    constructor_list_atom: $ => prec.right(1024, $._constructor),
    constructor_list_push: $ => prec.left(1024, seq($._constructor_list, ',', $._constructor)),
    datatype_decl: $ => seq('datatype', $.identifier, optional($._bindings), '{', $._constructor_list, '}'),
    command_datatypes: $ => seq(repeat($._datatype_decl), ';'),
    _expr: $ => choice($.not, $.number, $.bv1_lit, $.bv8_lit, $.bv16_lit, $.bv32_lit, $.bv64_lit, $.bv128_lit, $.string, $.decimal, $.if, $.old, $.map_get, $.map_set, $.seq_empty, $.seq_length, $.seq_select, $.seq_append, $.seq_build, $.seq_update, $.seq_contains, $.seq_take, $.seq_drop, $.str_len, $.str_concat, $.str_substr, $.str_toregex, $.str_inregex, $.str_prefixof, $.str_suffixof, $.re_allchar, $.re_all, $.re_range, $.re_concat, $.re_star, $.re_plus, $.re_loop, $.re_union, $.re_inter, $.re_comp, $.re_none, $.btrue, $.bfalse, $.equiv, $.implies, $.and, $.or, $.equal, $.not_equal, $.le, $.lt, $.ge, $.gt, $.neg_expr, $.add_expr, $.sub_expr, $.mul_expr, $.div_expr, $.mod_expr, $.safediv_expr, $.safemod_expr, $.divt_expr, $.modt_expr, $.safedivt_expr, $.safemodt_expr, $.bvnot, $.bvand, $.bvor, $.bvxor, $.bvshl, $.bvushr, $.bvsshr, $.bvsdiv, $.bvsmod, $.safeadd_expr, $.safesub_expr, $.safemul_expr, $.safeneg_expr, $.safesdiv_expr, $.safesmod_expr, $.bvslt, $.bvsle, $.bvsgt, $.bvsge, $.bv_neg_overflow, $.bv_uneg_overflow, $.bv_sadd_overflow, $.bv_ssub_overflow, $.bv_smul_overflow, $.bv_sdiv_overflow, $.bv_uadd_overflow, $.bv_usub_overflow, $.bv_umul_overflow, $.bvconcat8, $.bvconcat16, $.bvconcat32, $.bvextract_7_7, $.bvextract_15_15, $.bvextract_31_31, $.bvextract_7_0_16, $.bvextract_7_0_32, $.bvextract_15_0_32, $.bvextract_7_0_64, $.bvextract_15_0_64, $.bvextract_31_0_64, $.lambda, $.apply_expr, $.forall, $.exists, $.forall_t, $.exists_t, $.identifier, seq('(', $._expr, ')')),
    not: $ => prec.right(1024, seq('!', $._expr)),
    bv1_lit: $ => seq('bv{1}', '(', $.number, ')'),
    bv8_lit: $ => seq('bv{8}', '(', $.number, ')'),
    bv16_lit: $ => seq('bv{16}', '(', $.number, ')'),
    bv32_lit: $ => seq('bv{32}', '(', $.number, ')'),
    bv64_lit: $ => seq('bv{64}', '(', $.number, ')'),
    bv128_lit: $ => seq('bv{128}', '(', $.number, ')'),
    if: $ => seq('if', $._expr, 'then', $._expr, 'else', $._expr),
    old: $ => prec.right(1024, seq('old', $._expr)),
    map_get: $ => seq($._expr, '[', $._expr, ']'),
    map_set: $ => seq($._expr, '[', $._expr, ':=', $._expr, ']'),
    seq_empty: $ => seq('Sequence.empty', '<', $._type, '>', '(', ')'),
    seq_length: $ => seq('Sequence.length', '(', $._expr, ')'),
    seq_select: $ => seq('Sequence.select', '(', $._expr, ',', $._expr, ')'),
    seq_append: $ => seq('Sequence.append', '(', $._expr, ',', $._expr, ')'),
    seq_build: $ => seq('Sequence.build', '(', $._expr, ',', $._expr, ')'),
    seq_update: $ => seq('Sequence.update', '(', $._expr, ',', $._expr, ',', $._expr, ')'),
    seq_contains: $ => seq('Sequence.contains', '(', $._expr, ',', $._expr, ')'),
    seq_take: $ => seq('Sequence.take', '(', $._expr, ',', $._expr, ')'),
    seq_drop: $ => seq('Sequence.drop', '(', $._expr, ',', $._expr, ')'),
    str_len: $ => seq('str.len', '(', $._expr, ')'),
    str_concat: $ => seq('str.concat', '(', $._expr, ',', $._expr, ')'),
    str_substr: $ => seq('str.substr', '(', $._expr, ',', $._expr, ',', $._expr, ')'),
    str_toregex: $ => seq('str.to.re', '(', $._expr, ')'),
    str_inregex: $ => seq('str.in.re', '(', $._expr, ',', $._expr, ')'),
    str_prefixof: $ => seq('str.prefixof', '(', $._expr, ',', $._expr, ')'),
    str_suffixof: $ => seq('str.suffixof', '(', $._expr, ',', $._expr, ')'),
    re_allchar: $ => seq('re.allchar', '(', ')'),
    re_all: $ => seq('re.all', '(', ')'),
    re_range: $ => seq('re.range', '(', $._expr, ',', $._expr, ')'),
    re_concat: $ => seq('re.concat', '(', $._expr, ',', $._expr, ')'),
    re_star: $ => seq('re.*', '(', $._expr, ')'),
    re_plus: $ => seq('re.+', '(', $._expr, ')'),
    re_loop: $ => seq('re.loop', '(', $._expr, ',', $._expr, ',', $._expr, ')'),
    re_union: $ => seq('re.union', '(', $._expr, ',', $._expr, ')'),
    re_inter: $ => seq('re.inter', '(', $._expr, ',', $._expr, ')'),
    re_comp: $ => seq('re.comp', '(', $._expr, ')'),
    re_none: $ => seq('re.none', '(', ')'),
    btrue: $ => 'true',
    bfalse: $ => 'false',
    equiv: $ => prec.left(4, seq($._expr, '<==>', $._expr)),
    implies: $ => prec.right(5, seq($._expr, '==>', $._expr)),
    and: $ => prec.left(10, seq($._expr, '&&', $._expr)),
    or: $ => prec.left(8, seq($._expr, '||', $._expr)),
    equal: $ => prec.left(15, seq($._expr, '==', $._expr)),
    not_equal: $ => prec.left(15, seq($._expr, '!=', $._expr)),
    le: $ => prec.left(15, seq($._expr, '<=', $._expr)),
    lt: $ => prec.left(15, seq($._expr, '<', $._expr)),
    ge: $ => prec.left(15, seq($._expr, '>=', $._expr)),
    gt: $ => prec.left(15, seq($._expr, '>', $._expr)),
    neg_expr: $ => prec.right(1024, seq('-', $._expr)),
    add_expr: $ => prec.left(25, seq($._expr, '+', $._expr)),
    sub_expr: $ => prec.left(25, seq($._expr, '-', $._expr)),
    mul_expr: $ => prec.left(30, seq($._expr, '*', $._expr)),
    div_expr: $ => prec.left(30, seq($._expr, 'div', $._expr)),
    mod_expr: $ => prec.left(30, seq($._expr, 'mod', $._expr)),
    safediv_expr: $ => prec.left(30, seq($._expr, '/', $._expr)),
    safemod_expr: $ => prec.left(30, seq($._expr, '%', $._expr)),
    divt_expr: $ => seq('Int.DivT(', $._expr, ',', $._expr, ')'),
    modt_expr: $ => seq('Int.ModT(', $._expr, ',', $._expr, ')'),
    safedivt_expr: $ => prec.left(30, seq($._expr, '/t', $._expr)),
    safemodt_expr: $ => prec.left(30, seq($._expr, '%t', $._expr)),
    bvnot: $ => prec.right(1024, seq('~', $._expr)),
    bvand: $ => prec.left(20, seq($._expr, '&', $._expr)),
    bvor: $ => prec.left(20, seq($._expr, '|', $._expr)),
    bvxor: $ => prec.left(20, seq($._expr, '^', $._expr)),
    bvshl: $ => prec.left(20, seq($._expr, '<<', $._expr)),
    bvushr: $ => prec.left(20, seq($._expr, '>>', $._expr)),
    bvsshr: $ => prec.left(20, seq($._expr, '>>s', $._expr)),
    bvsdiv: $ => prec.left(20, seq($._expr, 'sdiv', $._expr)),
    bvsmod: $ => prec.left(20, seq($._expr, 'smod', $._expr)),
    safeadd_expr: $ => prec.left(25, seq($._expr, 'safe+', $._expr)),
    safesub_expr: $ => prec.left(25, seq($._expr, 'safe-', $._expr)),
    safemul_expr: $ => prec.left(30, seq($._expr, 'safe*', $._expr)),
    safeneg_expr: $ => prec.right(1024, seq('safe_neg', $._expr)),
    safesdiv_expr: $ => prec.left(20, seq($._expr, 'safesdiv', $._expr)),
    safesmod_expr: $ => prec.left(20, seq($._expr, 'safesmod', $._expr)),
    bvslt: $ => prec.left(20, seq($._expr, '<s', $._expr)),
    bvsle: $ => prec.left(20, seq($._expr, '<=s', $._expr)),
    bvsgt: $ => prec.left(20, seq($._expr, '>s', $._expr)),
    bvsge: $ => prec.left(20, seq($._expr, '>=s', $._expr)),
    bv_neg_overflow: $ => seq('Bv.SNegOverflow', '(', $._expr, ')'),
    bv_uneg_overflow: $ => seq('Bv.UNegOverflow', '(', $._expr, ')'),
    bv_sadd_overflow: $ => seq('Bv.SAddOverflow', '(', $._expr, ',', $._expr, ')'),
    bv_ssub_overflow: $ => seq('Bv.SSubOverflow', '(', $._expr, ',', $._expr, ')'),
    bv_smul_overflow: $ => seq('Bv.SMulOverflow', '(', $._expr, ',', $._expr, ')'),
    bv_sdiv_overflow: $ => seq('Bv.SDivOverflow', '(', $._expr, ',', $._expr, ')'),
    bv_uadd_overflow: $ => seq('Bv.UAddOverflow', '(', $._expr, ',', $._expr, ')'),
    bv_usub_overflow: $ => seq('Bv.USubOverflow', '(', $._expr, ',', $._expr, ')'),
    bv_umul_overflow: $ => seq('Bv.UMulOverflow', '(', $._expr, ',', $._expr, ')'),
    bvconcat8: $ => seq('bvconcat{8}{8}', '(', $._expr, ',', $._expr, ')'),
    bvconcat16: $ => seq('bvconcat{16}{16}', '(', $._expr, ',', $._expr, ')'),
    bvconcat32: $ => seq('bvconcat{32}{32}', '(', $._expr, ',', $._expr, ')'),
    bvextract_7_7: $ => seq('bvextract{7}{7}{8}', '(', $._expr, ')'),
    bvextract_15_15: $ => seq('bvextract{15}{15}{16}', '(', $._expr, ')'),
    bvextract_31_31: $ => seq('bvextract{31}{31}{32}', '(', $._expr, ')'),
    bvextract_7_0_16: $ => seq('bvextract{7}{0}{16}', '(', $._expr, ')'),
    bvextract_7_0_32: $ => seq('bvextract{7}{0}{32}', '(', $._expr, ')'),
    bvextract_15_0_32: $ => seq('bvextract{15}{0}{32}', '(', $._expr, ')'),
    bvextract_7_0_64: $ => seq('bvextract{7}{0}{64}', '(', $._expr, ')'),
    bvextract_15_0_64: $ => seq('bvextract{15}{0}{64}', '(', $._expr, ')'),
    bvextract_31_0_64: $ => seq('bvextract{31}{0}{64}', '(', $._expr, ')'),
    lambda: $ => seq('fun', $._decl_list, '=>', $._expr),
    apply_expr: $ => seq('(', $._expr, ')', '(', $._expr, ')'),
    forall: $ => seq('forall', $._decl_list, '::', $._expr),
    exists: $ => seq('exists', $._decl_list, '::', $._expr),
    forall_t: $ => seq('forall', $._decl_list, '::', $._triggers, $._expr),
    exists_t: $ => seq('exists', $._decl_list, '::', $._triggers, $._expr),
    _type: $ => prec.left(choice($._type_atom, seq($._type, $._type_atom))),
    _type_atom: $ => choice('bool', 'int', 'string', 'regex', 'real', 'bv1', 'bv8', 'bv16', 'bv32', 'bv64', 'bv128', 'Map', 'Sequence', $.identifier, seq('(', $._type, ')')),
    comment: $ => token(seq('//', /.*/)),
    identifier: $ => /[A-Za-z_$][A-Za-z0-9_$]*/,
    number: $ => /[0-9]+/,
    decimal: $ => /[0-9]+\.[0-9]+/,
    string: $ => /"([^"\\]|\\.)*"/,
  }
});
