/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/
module

/--
Generates Strata/Examples/EmbeddedData.lean by scanning the Examples/ directory
and writing include_str entries for each file.

Usage:
  lake exe GenerateEmbedded          -- regenerate EmbeddedData.lean
  lake exe GenerateEmbedded --check  -- verify it matches what's checked in
-/

partial def collectFiles (base root : System.FilePath) : IO (Array String) := do
  let mut results := #[]
  for entry in ← System.FilePath.readDir root do
    if ← entry.path.isDir then
      results := results ++ (← collectFiles base entry.path)
    else
      let relPath := entry.path.toString.dropPrefix (base.toString ++ "/") |>.toString
      if relPath.endsWith ".st" || relPath.endsWith ".expected" || relPath.endsWith ".args" then
        results := results.push relPath
  return results

def generateContent (files : Array String) : String :=
  let mut content := ""
  content := content ++ "/-\n  Copyright Strata Contributors\n\n  SPDX-License-Identifier: Apache-2.0 OR MIT\n-/\n"
  content := content ++ "module\n\n"
  content := content ++ "-- Generated by: lake exe GenerateEmbedded\n"
  content := content ++ "-- Do not edit manually.\n\n"
  content := content ++ "/-- Embedded example files for use by downstream test suites. -/\n"
  content := content ++ "public def embeddedExampleFiles : Array (String × String) := #[\n"
  for (i, file) in files.toList.enum do
    let comma := if i < files.size - 1 then "," else ""
    content := content ++ s!"  (\"{file}\", include_str \"../../Examples/{file}\"){comma}\n"
  content := content ++ "]\n"
  content

def main (args : List String) : IO UInt32 := do
  let examplesDir : System.FilePath := "Examples"
  let files ← collectFiles examplesDir examplesDir
  let sorted := files.toList.mergeSort (· < ·) |>.toArray

  let outputPath : System.FilePath := "Strata" / "Examples" / "EmbeddedData.lean"
  let generated := generateContent sorted

  if args.contains "--check" then
    let existing ← IO.FS.readFile outputPath
    if existing == generated then
      IO.println s!"✓ {outputPath} is up to date ({sorted.size} files)"
      return 0
    else
      IO.eprintln s!"✗ {outputPath} is out of date. Run 'lake exe GenerateEmbedded' to regenerate."
      return 1
  else
    IO.FS.writeFile outputPath generated
    IO.println s!"Generated {outputPath} with {sorted.size} files"
    return 0
