name: BoogieToStrata CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  SOLUTION: Tools/BoogieToStrata/BoogieToStrata.sln
  Z3URL: https://github.com/Z3Prover/z3/releases/download/z3-4.15.2/z3-4.15.2-x64-glibc-2.39.zip
  CVC5URL: https://github.com/cvc5/cvc5/releases/download/cvc5-1.3.0/cvc5-Linux-x86_64-static.zip

jobs:
  build_and_test:
    name: BoogieToStrata CI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install solvers
        run: |
          # Download a Z3 release
          wget ${Z3URL}
          unzip z3*.zip
          find $PWD/z3* -name bin -type d >> $GITHUB_PATH
          # Download a cvc5 release
          wget ${CVC5URL}
          unzip cvc5*.zip
          find $PWD/cvc5* -name bin -type d >> $GITHUB_PATH
      - name: Test solvers
        run: |
          z3 --version
          cvc5 --version
      - name: Setup Lean
        uses: leanprover/lean-action@v1
        with:
          build: false
          test: false
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build StrataVerify
        run: lake exe StrataVerify Examples/SimpleProc.boogie.st
      - name: Build BoogieToStrata
        run: |
          dotnet build -warnaserror ${SOLUTION}
      - name: Test BoogieToStrata
        run: |
          dotnet test ${SOLUTION}